### ISSUE TITLE
cif-smrt: 500 and 502 errors

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#144]
Installed alpha-14 and let it run for 18+ hours. I see the following in the cf-smrt.log

```bash
[2015-01-21T12:48:44,488Z][ERROR]: 500 Internal Server Error
[2015-01-21T14:48:34,973Z][ERROR]: 500 Internal Server Error
[2015-01-21T16:48:29,010Z][ERROR]: 502 Proxy Error
[2015-01-21T18:48:41,824Z][ERROR]: 500 Internal Server Error
[2015-01-21T21:48:46,585Z][ERROR]: 500 Internal Server Error
```
nothing in any of the cif, apache or elasticsearch logs that might indicate what the problem is.

**Comment by wesyoung** [comment]
hrm, i looked through 2 weeks of logs on my box, don't see it. once we push new release, we'll open this back up if it crops back in.

**Comment by cjhc** [comment]
Hey guys ;) Testing 2.00.00-beta.2cif on Ubuntu 14.04 LTS 64-bit behind an http_proxy (which also un-easys the easy-button, but I'll leave that aside).

"sudo -u cif /opt/cif/bin/cif-smrt --testmode -d" works, other than 500 SSL upgrade failed errors even with --no-verify-ssl appended. Feeds are pulled.

When the cif-smrt service is started back up (--test-mode appended to run immediately), I get timeouts for the feeds. My theory is that start-stop-daemon in Ubuntu is ignoring http_proxy environment variables, and of course the Ubuntu version of start-stop-daemon doesn't use the -e or --env flags to set them within the init.d script. I have yet to find a way to get the environment variables to be respected when run as a daemon from init.d. I had the problem as well on previous alpha releases.

Here is an example from cif-smrt.log:
#[2015-04-08T15:14:23,022Z][DEBUG][main:308]: spamhaus.org - drop
#[2015-04-08T15:14:23,022Z][INFO][main:310]: processing: -r /etc/cif/rules/default/spamhaus.yml -f drop
#[2015-04-08T15:14:23,023Z][DEBUG][CIF::Smrt:93]: starting at: 2015-04-08T00:00:00Z
#[2015-04-08T15:14:23,023Z][DEBUG][CIF::Smrt:98]: fetching...
#[2015-04-08T15:14:23,024Z][DEBUG][CIF::Smrt::Fetcher:81]: pulling: http://www.spamhaus.org/drop/drop.lasso
#[2015-04-08T15:14:51,438Z][DEBUG][CIF::Smrt::Fetcher:97]: status: 500 Can't connect to s3.amazonaws.com:80 (Connection timed out)
#[2015-04-08T15:14:51,438Z][ERROR][CIF::Smrt::Fetcher:99]: 500 Can't connect to s3.amazonaws.com:80 (Connection timed out)
#[2015-04-08T15:14:51,439Z][DEBUG][CIF::Smrt:101]: no data.. skipping..
#[2015-04-08T15:14:51,439Z][INFO][main:342]: nothing new to send...

When I run the command (with sudo) setup by start-stop-daemon, it pulls feeds.
#$ sudo /usr/bin/perl /opt/cif/bin/cif-smrt -d --logging --logfile /var/log/cif-smrt.log -p /var/run/cif-smrt.pid -C /etc/cif/cif-smrt.yml -D start --testmode

**Comment by cjhc** [comment]
Quick update... it looks like the recurring 60 min interval run of the feed pull when started via sudo command above also reliably times out.

I've disabled the cif-smrt service, commented out cif-smrt in monitrc, and added an hourly run to crontab like the approach in v1:
> 05      *       * * * /opt/cif/bin/cif-smrt -d --logging --logfile /var/log/cif-smrt.log -p /var/run/cif-smrt.pid -C /etc/cif/cif-smrt.yml --testmode

I will do some further testing to determine if the problem is restricted to cif-smrt running as a daemon when started via start-stop-daemon, or if it does extend to it being started as a daemon via commandline.

**Comment by giovino** [comment]
@cjhc thanks for the report, gives us a little bit of time to chase this one down.

**Comment by wesyoung** [comment]
can you dump what your proxy ENV vars look like? (sanitize them to something like proxy.example.com)

something like:

perl -e 'use Data::Dumper; warn Dumper(%ENV)'

**Comment by wesyoung** [comment]
also, logging this as a new issue since it's un-related to what #144 orig was.
