### ISSUE TITLE
cif-smrt no output without debug

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#150]
When trying to explore the usage of cif-smrt I ran ```/opt/cif/bin/cif-smrt``` thinking I would get the help screen as I gave it no arguments. 

Instead I was presented this:

```
# /opt/cif/bin/cif-smrt

```

I first thought cif-smrt was in a hung state as it was missing a required argument. After poking around I suspect it is in it's random start stage but you don't know what's happening unless you use the debug argument. 

```
# /opt/cif/bin/cif-smrt -d
[2015-02-21T14:09:55,788Z][DEBUG][main:250]: random start set to: 17
[2015-02-21T14:09:55,789Z][INFO][main:252]: delaying start for: 17min then running every 60min there after...
[2015-02-21T14:09:55,789Z][INFO][main:253]: to run immediately, set: --randomstart 0 or --testmode
```

What are your thoughts about displaying some text to stdout if cif-smrt is in it's random start state to give the user more information on what is going on?

**Comment by wesyoung** [comment]
hrm, this one is tricky. technically cif-smrt is running as a daemon, so with "no options" it does the default thing. i cleaned up some of the logging configs:

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/hacking/packaging/ubuntu/init.d/cif-smrt#L50

which comes from /etc/default/cif:

CIF_DEBUGGING="-d"

other-wise, cif-smrt starts up logging in "ERROR" mode; which is higher than 'INFO' (meaning, you'll only output 'ERROR').

see what:

https://github.com/csirtgadgets/massive-octo-spice/commit/479c7c3218583e5117faeb83435b749dbaa124cd

does for ya. it figures out "you're not running as daemon" and increases the loglevel +2 (ERROR to WARNING to INFO).
