### ISSUE TITLE
easybutton - ubuntu

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/massive-octo-spice#153]
I was following the wiki for Ubuntu 14, but it fails by not finding add-apt-repository. In Ubuntu 14, add-apt-repository is provided by software-properties-common not python-software-properties. Can you add a fix in /platforms/ubuntu/ubuntu.sh (maybe a test for lsb_release -sr)?

checking with user to see if they are using the 32bit version, doesn't seem to be 'broken' in trusty64

**Comment by wesyoung** [comment]
```
vagrant@vagrant-ubuntu-trusty-64:~$ aptitude search software-properties
i   python-software-properties                                                                       - manage the repositories that you install software from                                                     
i   python3-software-properties                                                                      - manage the repositories that you install software from                                                     
i   software-properties-common                                                                       - manage the repositories that you install software from (common)                                            
p   software-properties-gtk                                                                          - manage the repositories that you install software from (gtk)                                               
p   software-properties-kde                                                                          - manage the repositories that you install software from (kde)         
```

**Comment by willfroning** [comment]
Hello Wes,

By default Ubuntu 14 does install software-properties-common. You can close this issue since it's very much a problem with my environment. 

It all was because I was using Phusion's Vagrant box (https://vagrantcloud.com/phusion/boxes/ubuntu-14.04-amd64) for testing and it lacks software-properties-common.

Thanks and sorry for the noise.

-Will

**Comment by wesyoung** [comment]
no worries, just wanted to be sure. if you haven't already, check out:

https://vagrantcloud.com/wesyoung/boxes/cif_base

it's pre-installed with most of the perl deps (minus all the cif specific stuff, still have to run easybutton).

hth,
