### ISSUE TITLE
How does GeoLite2-City.mmdb get updated?

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#157]
GeoLite2-City.mmdb appears to be downloaded in the Makefile during installation. How does this file get updated over time? I did not see any assoicated cronjobs.

**Comment by wesyoung** [comment]
it doesn't. maybe should...

**Comment by giovino** [comment]
I'm guessing it should ;)

"GeoLite2 databases are updated on the first Tuesday of each month."
http://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by wesyoung** [comment]
https://github.com/maxmind/geoipupdate
