### ISSUE TITLE
2.00.00-alpha.15 - memory leak

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#165]
2.00.00-alpha.15

On a clean install of 2.00.00-alpha.15 on Ubuntu 14.04.02 on a VM with 8 GB ram, 8 GB swap, 2 cores, after five days of running, I found the VM with all ram and all swap used up. 

There may be a few entries of in the logs that are interesting. 

https://transfer.sh/IKXHK/cif.logs.tar.gz.gpg

gpg password will be in your email.

**Comment by wesyoung** [comment]
this should be fixed in @develop
