### ISSUE TITLE
Explore forcing cpan try harder to download modules

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#168]
Example reason:

```
Fetching http://www.cpan.org/authors/id/S/SA/SALVA/Math-Int128-0.21.tar.gz ... FAIL
! Download http://www.cpan.org/authors/id/S/SA/SALVA/Math-Int128-0.21.tar.gz failed. Retrying ... 
! Download http://www.cpan.org/authors/id/S/SA/SALVA/Math-Int128-0.21.tar.gz failed. Retrying ... 
! Download http://www.cpan.org/authors/id/S/SA/SALVA/Math-Int128-0.21.tar.gz failed. Retrying ... 
! Failed to download http://www.cpan.org/authors/id/S/SA/SALVA/Math-Int128-0.21.tar.gz
! Failed to fetch distribution Math-Int128-0.21
```

**Comment by wesyoung** [comment]
cpan.org has these failures from time to time... :-/

what i've done in the past is something like:

https://github.com/csirtgadgets/massive-octo-spice/blob/master/hacking/platforms/ubuntu/ubuntu.sh#L47

where we use metacpan or similar... (if not straight up github anymore).

**Comment by giovino** [comment]
Wes,

What do you think about the following for changes to make the installation more fault tolerant. 

https://github.com/giovino/massive-octo-spice/commit/4cff348a89ef11b46c0116cf4d6490c6e857f604

1. It certainly makes the downloading of the intial packages more fault tolerant. 
2. It does little to help when cpanm is downloading dependicies
3. It specifics two packages by exact version number (Regexp::Common & Mouse)

Thoughts?

-g

**Comment by giovino** [comment]
Round two

Not sure how I missed this in the first place.. how about telling cpanm to use wget instead of LWP

```
--wget
    Uses GNU Wget (if available) to download stuff.

Normally with --lwp, --wget and --curl options set to true (which is the default) cpanm
tries LWP, Wget, cURL and HTTP::Tiny (in that order) and uses the first one available.
```
Reference:
http://search.cpan.org/~miyagawa/App-cpanminus-1.7027/bin/cpanm
