### ISSUE TITLE
 ics.sans.edu parser improvment request

### ISSUE THREAD

**Issue by audrjon** [csirtgadgets/massive-octo-spice#170]
Hi,

I just found and want to let you know, that some domains from ics.sans.edu are not correctly parsed.
For example in elasticsearch, I have found some observable like:
isc.sans.edu -alpha.ooo.al 75 suspicious 2015-03-10T07:00:35Z 2015-03-10T07:00:35Z 
isc.sans.edu -analytics.net 75 suspicious 2015-03-10T07:00:35Z 2015-03-10T07:00:35Z 
isc.sans.edu -aviatour.com 75 suspicious 2015-03-10T07:00:35Z 2015-03-10T07:00:35Z 
isc.sans.edu -chambers.com 75 suspicious 2015-03-10T07:00:35Z 2015-03-10T07:00:35Z 
isc.sans.edu -i-o-v.ru 75 suspicious 2015-03-10T07:00:35Z 2015-03-10T07:00:35Z 
isc.sans.edu -ina.com 75 suspicious 2015-03-10T07:00:35Z 2015-03-10T07:00:35Z 
isc.sans.edu -n-d-the.com 75 suspicious 2015-03-10T07:00:35Z 2015-03-10T07:00:35Z

			

But in reality they are:
p-alpha.ooo.al
m-analytics.net 
n-aviatour.com
a-chambers.com
b-i-o-v.ru 
a-n-d-the.com

If we try to find it using cif, we can get second output:
admin@srv-030:~$ cif -q -alpha.ooo.al
tlp  |group   |reporttime          |observable   |cc|asn|confidence|tags      |rdata|provider    |application
amber|everyone|2015-03-08T15:02:23Z|-alpha.ooo.al|  |   |75        |suspicious|     |isc.sans.edu|
amber|everyone|2015-03-10T00:34:06Z|-alpha.ooo.al|  |   |65        |suspicious|     |isc.sans.edu|
amber|everyone|2015-03-10T07:00:28Z|-alpha.ooo.al|  |   |75        |suspicious|     |isc.sans.edu|

admin@srv-030:~$ cif -q p-alpha.ooo.al
tlp  |group   |reporttime          |observable    |cc|asn|confidence|tags       |rdata|provider            |application
amber|everyone|2015-03-08T15:04:01Z|p-alpha.ooo.al|  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|
amber|everyone|2015-03-10T00:35:36Z|p-alpha.ooo.al|  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|
amber|everyone|2015-03-10T07:02:14Z|p-alpha.ooo.al|  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|

**Comment by wesyoung** [comment]
fixed, will be included in alpha.17, ty!

**Comment by audrjon** [comment]
Hi wes,

I just checked and it seems, that this time after changing the regex code from previous one, it doesn't parse these feeds at all. When I changed the code back to '^[^Site](\S+)', it works, but it doesn't parse them correctly. 
The regex code witch should work is this "^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}" (with match at line breaks} turnen on. I tested it on http://regexpal.com/.
But if I put the same code in isc_sans_edu.yml, it doesn't work.
Because I am not regex guru, so I will leave it for you :)

Regards,
Audrius

**Comment by wesyoung** [comment]
this is a slightly different issue, i think they started adding "tabs" (\t) to the end of each address, and the parser wasn't stripping out the whitespace properly... pushed a new fix, should be in the beta.2 release...

tyty!

**Comment by audrjon** [comment]
Hi,

Yes I noticed this. But I thought, that for a correct regex, it shouldn't matter what additional "features"will be implemented in the future.
Thanks for a fix, I will check this out!
Happy Easter!

Audrius
