### ISSUE TITLE
IP's not listed in CIF DB after feeds are parsed

### ISSUE THREAD

**Issue by audrjon** [csirtgadgets/massive-octo-spice#172]
Issue described here: https://groups.google.com/forum/#!topic/ci-framework/nG-bNLaJHeY

To replicate it you should follow these steps:
1. Intsall Ubuntu 14.04 TLS
2. sudo apt-get update && sudo apt-get upgrade -y
3. Intsall cif v2:
curl -Ls https://raw.githubusercontent.com/csirtgadgets/massive-octo-spice/master/hacking/platforms/easybutton_curl.sh | sudo bash -
sudo chown `whoami`:`whoami` ~/.cif.yml

4. Test if cif is working:
audrius@cifv2:~$ cif -p
roundtrip: 0.679375 ms
roundtrip: 0.66907 ms
roundtrip: 0.708027 ms
roundtrip: 0.712459 ms

5. Stop all cif processes:
service cif-router stop
service cif-starman stop
service cif-worker stop
service cif-smrt stop

6. Delete cif.observable index if exists:
curl -XDELETE localhost:9200/cif.observables-2015.03.13

audrius@cifv2:~$ curl -XDELETE localhost:9200/cif.observables-2015.03.13
{"error":"IndexMissingException[[cif.observables-2015.03.13] missing]","status":404}audrius@cifv2:~$ 
audrius@cifv2:~$ 

Because, there is no index created, we got an error. So, this is ok.

7.Delete /var/smrt/cache content
audrius@cifv2:~$ sudo rm /var/smrt/cache/*

8. Start services without cif-worker (we want test IP's if they exists in cif, so we don't need worker)
sudo service cif-starman start
sudo service cif-router start
sudo service cif-smrt start

9. Execute test and wait:
sudo -u cif /opt/cif/bin/cif-smrt --testmode -d

10. Check contents of /var/smrt/cache
audrius@cifv2:~$ ls /var/smrt/cache/
20150313.log                        dshield.org-scanners               openphish.com-urls
alexa.com-top10                     feodotracker.abuse.ch-domains      phishtank.com-urls
alexa.com-top100                    feodotracker.abuse.ch-ips          spamhaus.org-drop
alexa.com-top1000                   id4.us-ssh                         spamhaus.org-edrop
alexa.com-top10000                  isc.sans.edu-domains_high          spyeyetracker.abuse.ch-binaries
anti-phishing-email-reply-content   isc.sans.edu-domains_low           spyeyetracker.abuse.ch-configs
anti-phishing-email-reply-header    isc.sans.edu-domains_medium        spyeyetracker.abuse.ch-domains
arbor.com-ssh                       malc0de.com-urls                   spyeyetracker.abuse.ch-dropzones
bambenekconsulting.com-goz_domains  malwaredomains.com-domains         spyeyetracker.abuse.ch-ip
bambenekconsulting.com-goz_ip       malwaredomains.com-registrars      zeustracker.abuse.ch-binaries
botscout.com-bots                   malwaredomains.com-url_shorteners  zeustracker.abuse.ch-configs
danger.rulez.sk-ssh                 mirc.com-domains                   zeustracker.abuse.ch-domains
dragonresearchgroup.org-ssh         nothink.org-ssh                    zeustracker.abuse.ch-dropzones
dragonresearchgroup.org-vnc         openbl.org-scanners                zeustracker.abuse.ch-ip

11. Check if we have IP's:
audrius@cifv2:~$ cif -p
roundtrip: 0.113349 ms
roundtrip: 0.103747 ms
roundtrip: 0.083777 ms
roundtrip: 0.056899 ms
audrius@cifv2:~$ cif --confidence 5 --otype ipv4 -l 10
audrius@cifv2:~$ 
audrius@cifv2:~$ 

No results found

12. Check if do we have any records:
audrius@cifv2:~$ cif --confidence 5  -l 10

tlp  |group   |reporttime          |observable              |cc|asn|confidence|tags       |rdata|provider            |application
amber|everyone|2015-03-13T18:38:10Z|03a6f57.netsolhost.com  |  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|           
amber|everyone|2015-03-13T18:38:10Z|03bbec4.netsolhost.com  |  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|           
amber|everyone|2015-03-13T18:38:10Z|0x.x.gg                 |  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|           
amber|everyone|2015-03-13T18:38:10Z|4btc.cc                 |  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|           
amber|everyone|2015-03-13T18:38:10Z|a1b2c3d4.ru             |  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|           
amber|everyone|2015-03-13T18:38:10Z|anlacviettravel.com.vn  |  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|           
amber|everyone|2015-03-13T18:38:10Z|apexholdngs.com         |  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|           
amber|everyone|2015-03-13T18:38:10Z|artekteknikhirdavat.com |  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|           
amber|everyone|2015-03-13T18:38:10Z|ascottconsultants.com.ph|  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|           
amber|everyone|2015-03-13T18:38:10Z|auto-fx.fr              |  |   |65        |zeus,botnet|     |zeustracker.abuse.ch|           

audrius@cifv2:~$ 

So, we can found results, but no IP's despite we have them in some lists like
audrius@cifv2:/var/smrt/cache$ tail -f dragonresearchgroup.org-ssh 
133775       |  CHINATELECOM-FUJIAN-XIAMEN-IDC  |     218.5.74.119  |  2015-03-09 12:29:23  |  sshpwauth
197145       |  ASINFIUM Infium LLC,RU          |   188.190.115.58  |  2015-03-10 03:42:19  |  sshpwauth
199456       |  VLDTECH-ASN VALID TECHNOLOGY L  |    185.16.40.146  |  2015-03-06 20:08:51  |  sshpwauth
262145       |  Cooperativa de ElectrificaciÃ³  |    190.211.106.3  |  2015-03-06 20:54:59  |  sshpwauth
393406       |  DIGITALOCEAN-ASN-NY3 - Digital  |    104.236.22.62  |  2015-03-10 19:47:21  |  sshpwauth
393406       |  DIGITALOCEAN-ASN-NY3 - Digital  |    45.55.189.206  |  2015-03-11 09:48:17  |  sshpwauth
#
# Statistics
#        ASNs: 417
#   Addresses: 1044

**Comment by wesyoung** [comment]
i think this is related to #156

**Comment by audrjon** [comment]
Hi wes,

sorry for a delay... Yes, it may be related. Just testing it now and it seems, that it is working!
Thanks a lot!

**Comment by wesyoung** [comment]
rock on! :)
