### ISSUE TITLE
make storage remote configurable

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/massive-octo-spice#176]

**Comment by nixfloyd** [comment]
An easy work-around is to configure a reverse proxy in nginx/apache on localhost:9200, which forwards to the actual Elasticsearch host(s)

**Comment by wesyoung** [comment]
correct, i should have elaborated more, in that, we want cif-router to be able to configure an address for where ES is (it's configurable at the local level, but i dunno that we mapped configs to the actual configure bits).

that way cif-router can live on a different box than ES

(in v3: https://github.com/csirtgadgets/bearded-avenger we're making this even more spit out where the storage agents abstract it out a bit and simply log into cif-router for data)
