### ISSUE TITLE
v1 --> v2 data migration tool

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/massive-octo-spice#183]
https://github.com/collectiveintel/cif-v1/blob/master/libcif-dbi/sbin/migrate-data.pl

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/blob/develop/contrib/migrate-data.pl

**Comment by giovino** [comment]
We need some words for Chapter 9 Section 3.

https://github.com/csirtgadgets/massive-octo-spice/wiki/The-CIF-Book

What is our recommendation?

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/wiki/Migration
