### ISSUE TITLE
Install instructions + cif-smrt + monit

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#188]
Running through the install instructions for beta 1 I came across this scenerio:

1. ```sudo service cif-smrt stop```
1. ```sudo -u cif /opt/cif/bin/cif-smrt --testmode -d```
1. ```sudo service cif-smrt start```

cif-smrt testmode takes 3-4 minutes to complete. upon restarting cif-smrt it told me it was already started. 

I suspect this is because Monit restarted the cif-smrt service. What's the best way to account for this?

**Comment by wesyoung** [comment]
stop monit... ?

**Comment by wesyoung** [comment]
doc updated.
