### ISSUE TITLE
cif-smrt proxy issues

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/massive-octo-spice#191]
Hey guys ;) Testing 2.00.00-beta.2cif on Ubuntu 14.04 LTS 64-bit behind an http_proxy (which also un-easys the easy-button, but I'll leave that aside).

"sudo -u cif /opt/cif/bin/cif-smrt --testmode -d" works, other than 500 SSL upgrade failed errors even with --no-verify-ssl appended. Feeds are pulled.

When the cif-smrt service is started back up (--test-mode appended to run immediately), I get timeouts for the feeds. My theory is that start-stop-daemon in Ubuntu is ignoring http_proxy environment variables, and of course the Ubuntu version of start-stop-daemon doesn't use the -e or --env flags to set them within the init.d script. I have yet to find a way to get the environment variables to be respected when run as a daemon from init.d. I had the problem as well on previous alpha releases.

Here is an example from cif-smrt.log:
>[2015-04-08T15:14:23,022Z][DEBUG][main:308]: spamhaus.org - drop
>[2015-04-08T15:14:23,022Z][INFO][main:310]: processing: -r /etc/cif/rules/default/spamhaus.yml -f drop
>[2015-04-08T15:14:23,023Z][DEBUG][CIF::Smrt:93]: starting at: 2015-04-08T00:00:00Z
>[2015-04-08T15:14:23,023Z][DEBUG][CIF::Smrt:98]: fetching...
>[2015-04-08T15:14:23,024Z][DEBUG][CIF::Smrt::Fetcher:81]: pulling: http://www.spamhaus.org/drop/drop.lasso
>[2015-04-08T15:14:51,438Z][DEBUG][CIF::Smrt::Fetcher:97]: status: 500 Can't connect to s3.amazonaws.com:80 (Connection timed out)
>[2015-04-08T15:14:51,438Z][ERROR][CIF::Smrt::Fetcher:99]: 500 Can't connect to s3.amazonaws.com:80 (Connection timed out)
>[2015-04-08T15:14:51,439Z][DEBUG][CIF::Smrt:101]: no data.. skipping..
>[2015-04-08T15:14:51,439Z][INFO][main:342]: nothing new to send...

When I run the command (with sudo) setup by start-stop-daemon, it pulls feeds.
>$ sudo /usr/bin/perl /opt/cif/bin/cif-smrt -d --logging --logfile /var/log/cif-smrt.log -p /var/run/cif-smrt.pid -C /etc/cif/cif-smrt.yml -D start --testmode

**Comment by wesyoung** [comment]
Quick update... it looks like the recurring 60 min interval run of the feed pull when started via sudo command above also reliably times out.

I've disabled the cif-smrt service, commented out cif-smrt in monitrc, and added an hourly run to crontab like the approach in v1:
> 05      *       * * * /opt/cif/bin/cif-smrt -d --logging --logfile /var/log/cif-smrt.log -p /var/run/cif-smrt.pid -C /etc/cif/cif-smrt.yml --testmode

I will do some further testing to determine if the problem is restricted to cif-smrt running as a daemon when started via start-stop-daemon, or if it does extend to it being started as a daemon via commandline.

**Comment by wesyoung** [comment]
can you dump what your proxy ENV vars look like? (sanitize them to something like proxy.example.com)

something like:

`` perl -e 'use Data::Dumper; warn Dumper(%ENV)'  ``

**Comment by wesyoung** [comment]
via https://github.com/csirtgadgets/massive-octo-spice/issues/144

**Comment by wesyoung** [comment]
fwiw, this is what the LWP::UserAgent (the code that pulls the feeds) proxy function looks like:

```
sub env_proxy {
    my ($self) = @_;
    require Encode;
    require Encode::Locale;
    my($k,$v);
    while(($k, $v) = each %ENV) {
	if ($ENV{REQUEST_METHOD}) {
	    # Need to be careful when called in the CGI environment, as
	    # the HTTP_PROXY variable is under control of that other guy.
	    next if $k =~ /^HTTP_/;
	    $k = "HTTP_PROXY" if $k eq "CGI_HTTP_PROXY";
	}
	$k = lc($k);
	next unless $k =~ /^(.*)_proxy$/;
	$k = $1;
	if ($k eq 'no') {
	    $self->no_proxy(split(/\s*,\s*/, $v));
	}
	else {
            # Ignore random _proxy variables, allow only valid schemes
            next unless $k =~ /^$URI::scheme_re\z/;
            # Ignore xxx_proxy variables if xxx isn't a supported protocol
            next unless LWP::Protocol::implementor($k);
	    $self->proxy($k, Encode::decode(locale => $v));
	}
    }
}
```

**Comment by wesyoung** [comment]
i'm gonna release beta.3, in /etc/cif/cif-smrt.yml try adding something like:

```
---
client:
  remote: http://localhost:5000
  token: aaaa
  proxy: http://127.0.0.1:8080
```

**Comment by cjhc** [comment]
Sorry for the delay, I was traveling  the latter half of last week without access and then out of commission sick after getting back.

I've updated to the latest release, added the proxy to cif-smrt.yml, and it does appear to be working now! Well done, thanks Wes.

**Comment by wesyoung** [comment]
no worries, happens to me all-the-time... travel-sick-work-travel-sick-work... stupid planes and their stupid germs. :)
