### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by CingulateCortex** [csirtgadgets/massive-octo-spice#202]
Hi 

I cloned repo and ./configure make and when i try make install i got below error

```
root@beespp:/opt/massive-octo-spice# make install
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create --no-recursion
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for perl... /usr/bin/perl
checking for cpanm... not found
checking for curl... /usr/bin/curl
checking for gzip... /bin/gzip
checking that generated files are newer than configure... done
configure: creating ./config.status
 /bin/bash ./config.status
config.status: creating Makefile
config.status: creating src/Makefile.PL
config.status: creating src/lib/CIF/Generated.pm
config.status: creating elasticsearch/Makefile
config.status: creating hacking/packaging/ubuntu/default/cif
( cd src && make install )
make[1]: Entering directory '/opt/massive-octo-spice/src'
Makefile out-of-date with respect to Makefile.PL
Cleaning current config before rebuilding Makefile...
make -f Makefile.old clean > /dev/null 2>&1
/usr/bin/perl Makefile.PL "DESTDIR=" "INSTALL_BASE=/opt/cif" "INSTALLPRIVLIB=/opt/cif/lib/perl5"
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for CIF
==> Your Makefile has been rebuilt. <==
==> Please rerun the make command.  <==
false
Makefile:982: recipe for target 'Makefile' failed
make[1]: *** [Makefile] Error 1
make[1]: Leaving directory '/opt/massive-octo-spice/src'
Makefile:787: recipe for target 'install-files' failed
make: *** [install-files] Error 2
```

**Comment by CingulateCortex** [comment]
Additional error

 ( cd src && make install )
make[1]: Entering directory '/opt/massive-octo-spice/src'
Appending installation info to /opt/cif/lib/perl5/x86_64-linux-gnu-thread-multi/perllocal.pod
make[1]: Leaving directory '/opt/massive-octo-spice/src'
[ -d /opt/cif/etc/rules ] || /usr/bin/install -c -m 0770 -d /opt/cif/etc/rules
( cd src/rules && find . -type d -print ) | while read dir ; do \
        /usr/bin/install -c -m 0770 -d "/opt/cif/etc/rules/$dir" ; \
done
( cd src/rules && find . -type f -print ) | while read file ; do \
        /usr/bin/install -c -m 0660 "src/rules/$file" "/opt/cif/etc/rules/$file" ; \
done
[ -d /opt/cif/var ] || /usr/bin/install -c -m 0770 -d /opt/cif/var
geoip not enabled, skipping...

**Comment by CingulateCortex** [comment]
when i configure with ./configure --enable-geoip and then make and make install i got following error


Makefile:783: recipe for target 'install-geoip' failed
make: *** [install-geoip] Error 1

**Comment by wesyoung** [comment]
what platform are you testing this on? did you do a:

```
$ bash autogen.sh
```
first?

if you're using ubuntu, use the easy_button instructions from the wiki, if not, see:

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/hacking/platforms/ubuntu/ubuntu.sh#L138

and 

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/hacking/platforms/easybutton_curl.sh#L33

**Comment by CingulateCortex** [comment]
Hi actually i already used easybutton_curl.sh. script created massive-octo-spice directory and cloned something related installation files. i used first autogen.sh

then ./configure --enable-geoip --sysconfdir=/etc/cif --localstatedir=/var --prefix=/opt/cif

then make and make install. 

the server is ubuntu.

**Comment by wesyoung** [comment]
14.04 ?

**Comment by CingulateCortex** [comment]
14.10

**Comment by wesyoung** [comment]
ahhh, we haven't tested on 14.10, right now just 14.04 (LTS style releases)...  see:

https://github.com/csirtgadgets/massive-octo-spice/wiki#fine-print

can you re-try on LTS?

**Comment by CingulateCortex** [comment]
is there any manual to install v2 ? because it seems those scripts cannot install

**Comment by CingulateCortex** [comment]
btw you when you say easybutton.sh, you mean

after cloned the git repo directly running hacking/platform/easybutton.sh right? not dealing with ./configure make make install ?

**Comment by wesyoung** [comment]
correct. IT does the configure, make.. etc for you:

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/hacking/platforms/ubuntu/ubuntu.sh#L138

to do a "manual" install, it's just:

```
bash autogen.sh
./configure --enable-geoip --sysconfdir=/etc/cif --localstatedir=/var --prefix=/opt/cif
make && make deps NOTESTS=-n
make test
make install
make fixperms
make elasticsearch
```

but there's a bit of configuration that goes into "setting up the OS, and the app" too... think of the easy-button as sort of a reference implementation. you're obviously welcome to fork it, improve it for other distributions, we just have limited cycles in making sure the install works perfectly on all of them (esp those that re-release every few months...).
