### ISSUE TITLE
Post installation question

### ISSUE THREAD

**Issue by CingulateCortex** [csirtgadgets/massive-octo-spice#210]
hi

i installed cif with easybutton. is there anything i should do after installation in terms of config. Because i could not find database etc in the system. And what should be the next steps to get malware feeds? 

Thanks

**Comment by giovino** [comment]
There is nothing you "need" to do post installation in terms of configuration. Your best bet is to run through chapters 1-4 in the CIF book. 

The CIF book
https://github.com/csirtgadgets/massive-octo-spice/wiki/The-CIF-Book

As for generating feeds (chapter 5), that is one of the last things to be finished, stay tuned. 

You may also want to join the cif-users group, a lot of Q&A happens there. 

cif-users
https://groups.google.com/forum/#!forum/ci-framework

Thanks!
