### ISSUE TITLE
v1 --> v2 API key migration tool 

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#211]
Create a tool to facilitate the migration of API keys from v1 to v2

**Comment by wesyoung** [comment]
this might be tricky, since we moved from uuid's to sha1 sums'... should we just auto-generate new keys for users?

**Comment by wesyoung** [comment]
although maybe it doesn't matter since "token" doesnt' really care what the value is... (cept maybe in cif-router, would have to check the auth to see if we test for an actual sha1sum hash or not as being "a valid token")

**Comment by wesyoung** [comment]
i think because of the new style of doing things, we may just be better off generating new apikeys, have to think on this a bit...

https://github.com/collectiveintel/cif-v1/blob/master/libcif-dbi/bin/cif_apikeys_export

```
vagrant@precise64:/vagrant$ cif_apikeys_export
[{"revoked":null,"user":"root","groups":[],"read":1,"default_group":"8c864306-d21a-37b1-8705-746a786719bf","token":"30b00cfd-6806-404e-9ecf-5c4bc37673fa","write":null,"expires":null}]
```

**Comment by wesyoung** [comment]
this may have implications on the data migration too.

**Comment by giovino** [comment]
We need some words for Chapter 9 Section 2.

https://github.com/csirtgadgets/massive-octo-spice/wiki/The-CIF-Book

What is our recommendation?

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/wiki/Migration
