### ISSUE TITLE
Chrome and Firefox plugins

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#212]
+ finish flushing out submission bits
+ doc
+ test with FF
+ merge into master
+ submit to chrome store

https://github.com/csirtgadgets/cif-client-chrome/tree/develop

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/cif-browsers

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/cif-browsers/issues

**Comment by wesyoung** [comment]
everything should be up to date, needs some testing on Chrome and FF first, draft is at the chrome store just awaiting the a-OK from testing.

**Comment by wesyoung** [comment]
chrome is OK to test, FF gonna need some work... (on my end)

**Comment by wesyoung** [comment]
FF is a PITA, few issues thus far:

+ dev environment sucks
+ right now it's showing "incompatible" with v39 (minor glitch?)
+ lots of things changing, might be worth splitting out the js-sdk stuff now, forking chrome into it's own repo as well as another FF repo..

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/cif-firefox/issues/1
