### ISSUE TITLE
Elasticsearch repor gives signature error

### ISSUE THREAD

**Issue by CingulateCortex** [csirtgadgets/massive-octo-spice#218]
when i try to manually add got below error 

root@a:~/massive-octo-spice# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D27D666CD88E42B4
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.5ChdlFfjzO --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/chris-lea-zeromq.gpg --keyserver keyserver.ubuntu.com --recv-keys D27D666CD88E42B4
gpg: requesting key D88E42B4 from hkp server keyserver.ubuntu.com
?: keyserver.ubuntu.com: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

**Comment by CingulateCortex** [comment]
sorry forgot to add error itself. 

Fetched 941 kB in 8s (107 kB/s)
Reading package lists... Done
W: GPG error: http://packages.elasticsearch.org stable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D27D666CD88E42B4
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package geoipupdate

**Comment by giovino** [comment]
I am unable to replicate the issue on Ubuntu Server 14.04.02 64-bit. Are you doing something similar to this?

``` 
root@ubuntu01:~# wget -O - https://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add -
--2015-05-26 12:46:46--  https://packages.elasticsearch.org/GPG-KEY-elasticsearch
Resolving packages.elasticsearch.org (packages.elasticsearch.org)... 54.204.6.18, 23.23.110.166, 23.21.184.154, ...
Connecting to packages.elasticsearch.org (packages.elasticsearch.org)|54.204.6.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1768 (1.7K) [binary/octet-stream]
Saving to: ‘STDOUT’

100%[===================================================================================================================================>] 1,768       --.-K/s   in 0s      

2015-05-26 12:46:46 (197 MB/s) - written to stdout [1768/1768]

OK
```

```
root@ubuntu01:~# apt-key list
/etc/apt/trusted.gpg
--------------------
pub   1024D/437D05B5 2004-09-12
uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
sub   2048g/79164387 2004-09-12

pub   1024D/FBB75451 2004-12-30
uid                  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>

pub   4096R/C0B21F32 2012-05-11
uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

pub   4096R/EFE21092 2012-05-11
uid                  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

pub   2048R/D88E42B4 2013-09-16
uid                  Elasticsearch (Elasticsearch Signing Key) <dev_ops@elasticsearch.org>
sub   2048R/60D31954 2013-09-16
```

References:

CIF Installer
https://github.com/csirtgadgets/massive-octo-spice/blob/develop/hacking/platforms/ubuntu/ubuntu.sh#L20

ElasticSearch
https://www.elastic.co/guide/en/logstash/master/package-repositories.html

**Comment by CingulateCortex** [comment]
actually i am behind proxy and run easybutton and easy button give this error. I will try manually and let you know.

**Comment by wesyoung** [comment]
in theory, setting the env proxy vars before running the easy button *should* solve this (i think). wget and apt-get should respect them...

**Comment by CingulateCortex** [comment]
Hi 

I tried it behind proxy. normally apt-get doesnt respect system proxy it seems. i made apt conf with proxy settings. Not apt-get update etc are working but the output is given below. it seems wget is fetching elasticsearch certificate but it is not in the list of apt-key


root@server:~/massive-octo-spice# wget -O - https://packages.elasticsearch.org/GPG-KEY-elasticsearch
--2015-06-12 12:53:20--  https://packages.elasticsearch.org/GPG-KEY-elasticsearch
Connecting to 192.168.16.121:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 1768 (1.7K) [binary/octet-stream]
Saving to: âSTDOUTâ

 0% [                                       ] 0           --.-K/s              -----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.14 (GNU/Linux)

mQENBFI3HsoBCADXDtbNJnxbPqB1vDNtCsqhe49vFYsZN9IOZsZXgp7aHjh6CJBD
A+bGFOwyhbd7at35jQjWAw1O3cfYsKAmFy+Ar3LHCMkV3oZspJACTIgCrwnkic/9
CUliQe324qvObU2QRtP4Fl0zWcfb/S8UYzWXWIFuJqMvE9MaRY1bwUBvzoqavLGZ
j3SF1SPO+TB5QrHkrQHBsmX+Jda6d4Ylt8/t6CvMwgQNlrlzIO9WT+YN6zS+sqHd
1YK/aY5qhoLNhp9G/HxhcSVCkLq8SStj1ZZ1S9juBPoXV1ZWNbxFNGwOh/NYGldD
2kmBf3YgCqeLzHahsAEpvAm8TBa7Q9W21C8vABEBAAG0RUVsYXN0aWNzZWFyY2gg
KEVsYXN0aWNzZWFyY2ggU2lnbmluZyBLZXkpIDxkZXZfb3BzQGVsYXN0aWNzZWFy
Y2gub3JnPokBOAQTAQIAIgUCUjceygIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgEC
F4AACgkQ0n1mbNiOQrRzjAgAlTUQ1mgo3nK6BGXbj4XAJvuZDG0HILiUt+pPnz75
nsf0NWhqR4yGFlmpuctgCmTD+HzYtV9fp9qW/bwVuJCNtKXk3sdzYABY+Yl0Cez/
7C2GuGCOlbn0luCNT9BxJnh4mC9h/cKI3y5jvZ7wavwe41teqG14V+EoFSn3NPKm
TxcDTFrV7SmVPxCBcQze00cJhprKxkuZMPPVqpBS+JfDQtzUQD/LSFfhHj9eD+Xe
8d7sw+XvxB2aN4gnTlRzjL1nTRp0h2/IOGkqYfIG9rWmSLNlxhB2t+c0RsjdGM4/
eRlPWylFbVMc5pmDpItrkWSnzBfkmXL3vO2X3WvwmSFiQbkBDQRSNx7KAQgA5JUl
zcMW5/cuyZR8alSacKqhSbvoSqqbzHKcUQZmlzNMKGTABFG1yRx9r+wa/fvqP6OT
RzRDvVS/cycws8YX7Ddum7x8uI95b9ye1/Xy5noPEm8cD+hplnpU+PBQZJ5XJ2I+
1l9Nixx47wPGXeClLqcdn0ayd+v+Rwf3/XUJrvccG2YZUiQ4jWZkoxsA07xx7Bj+
Lt8/FKG7sHRFvePFU0ZS6JFx9GJqjSBbHRRkam+4emW3uWgVfZxuwcUCn1ayNgRt
KiFv9jQrg2TIWEvzYx9tywTCxc+FFMWAlbCzi+m4WD+QUWWfDQ009U/WM0ks0Kww
EwSk/UDuToxGnKU2dQARAQABiQEfBBgBAgAJBQJSNx7KAhsMAAoJENJ9ZmzYjkK0
c3MIAIE9hAR20mqJWLcsxLtrRs6uNF1VrpB+4n/55QU7oxA1iVBO6IFu4qgsF12J
TavnJ5MLaETlggXY+zDef9syTPXoQctpzcaNVDmedwo1SiL03uMoblOvWpMR/Y0j
6rm7IgrMWUDXDPvoPGjMl2q1iTeyHkMZEyUJ8SKsaHh4jV9wp9KmC8C+9CwMukL7
vM5w8cgvJoAwsp3Fn59AxWthN3XJYcnMfStkIuWgR7U2r+a210W6vnUxU4oN0PmM
cursYPyeV0NX/KQeUeNMwGTFB6QHS/anRaGQewijkrYYoTNtfllxIu9XYmiBERQ/
qPDlGRlOgVTd9xUfHFkzB52c70E=
=92oX
-----END PGP PUBLIC KEY BLOCK-----
100%[======================================>] 1,768       --.-K/s   in 0s

2015-06-12 12:53:21 (392 MB/s) - written to stdout [1768/1768]

root@sver:~/massive-octo-spice# apt-key list
/etc/apt/trusted.gpg
--------------------
pub   1024D/437D05B5 2004-09-12
uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
sub   2048g/79164387 2004-09-12

pub   1024D/FBB75451 2004-12-30
uid                  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>

pub   4096R/C0B21F32 2012-05-11
uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

pub   4096R/EFE21092 2012-05-11
uid                  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

/etc/apt/trusted.gpg.d/chris-lea-zeromq.gpg
-------------------------------------------
pub   1024R/C7917B12 2010-05-17
uid                  Launchpad chrislea
