### ISSUE TITLE
make dns forwarders more "build friendly"

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/massive-octo-spice#234]
https://groups.google.com/forum/#!topic/ci-framework/o_-9fL0Vv94

Geoip database is my current tripping point in the Ubuntu install from Easybutton.

 0curl: (6) Could not resolve host: geolite.maxmind.com
gzip: contrib/GeoLite2-City.mmdb.gz: No such file or directory

make: *** [geoip] Error 1

It seems the DNS forwarders are being set in named.conf.options to Google during install, which is blocked from my test network. I tried setting them back, but the script doesn't survive the maxmind update failure.

I rebuilt after editing named.conf.options in ~/massive-octo-spice/hacking/platforms/ubuntu/ and things appear to be fine now.

Is there a nicer way to set expected DNS forwarders at build time?

**Comment by wesyoung** [comment]
short-answer work-around might be pushing the dns changes to the end of the script(?)

**Comment by giovino** [comment]
reverted fix as it was broke.

**Comment by giovino** [comment]
see https://github.com/csirtgadgets/massive-octo-spice/issues/239 for the reason to revert change.
