### ISSUE TITLE
create dummy test framework for live data

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/massive-octo-spice#238]

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/blob/develop/src/t/50-router.t

**Comment by wesyoung** [comment]
so, for all intents, is this done?

**Comment by giovino** [comment]
I guesstimate we have about 70% coverage in the things we'd likely test. Examples of where we are missing coverage:

1. We are not testing every data type listed in these examples: 

https://github.com/csirtgadgets/massive-octo-spice/wiki/Introducing-the-CIF-client#examples

2. We are not testing that data makes it into feeds, we do test that data _doesn't_ make it into a feed (whitelisting and groups)

3. We do not test many of the filters. 

Do you want to us to create one last script that addresses many of these things? It's just time ;)

-g

**Comment by wesyoung** [comment]
i tihnk this is probably good enough for now, we can add more as we go and lump the rest as we build out v3...
