### ISSUE TITLE
cpanminus module cannot be find

### ISSUE THREAD

**Issue by CingulateCortex** [csirtgadgets/massive-octo-spice#242]
I am trying to fresh install. I got below error 

Setting up liblwp-protocol-https-perl (6.04-2ubuntu0.1) ...
Setting up libwww-perl (6.05-2) ...
Setting up libapache2-mod-perl2 (2.0.8+httpd24-r1449661-6ubuntu2) ...
apache2_invoke: Enable module perl
 Restarting web server apache2                                                                 [ OK ]
Setting up libapache2-reload-perl (0.12-2) ...
Setting up libcgi-emulate-psgi-perl (0.15-1) ...
Setting up libhttp-body-perl (1.19-1) ...
Setting up libplack-perl (1.0030-1) ...
Setting up starman (0.4008-1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Processing triggers for ca-certificates (20141019ubuntu0.14.04.1) ...
Updating certificates in /etc/ssl/certs... 0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....
done.
done.
installing cpanm...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314    0   314    0     0    551      0 --:--:-- --:--:-- --:--:--   550
100  295k  100  295k    0     0   391k      0 --:--:-- --:--:-- --:--:--  391k
! Finding App::cpanminus on cpanmetadb failed.

! cannot open file '/root/.cpanm/sources/http%www.cpan.org/02packages.details.txt.gz': No such file or directory opening compressed index
! Couldn't find module or a distribution App::cpanminus

**Comment by giovino** [comment]
It looks like cpanminus failed to install[1]. Try running this command on that new install:

```
 curl -L https://cpanmin.us | sudo perl - App::cpanminus
```

Here's what a successful cpanminus install looks like:

```
curl -L https://cpanmin.us | sudo perl - App::cpanminus
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314    0   314    0     0    509      0 --:--:-- --:--:-- --:--:--   508
100  295k  100  295k    0     0   207k      0  0:00:01  0:00:01 --:--:-- 1035k
--> Working on App::cpanminus
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7036.tar.gz ... OK
Configuring App-cpanminus-1.7036 ... OK
Building and testing App-cpanminus-1.7036 ... OK
Successfully installed App-cpanminus-1.7036
1 distribution installed
```

[1] https://github.com/giovino/massive-octo-spice/blob/develop/hacking/platforms/ubuntu/ubuntu.sh#L45

**Comment by CingulateCortex** [comment]
curl -L https://cpanmin.us | sudo perl - App::cpanminus

in this command somehow when i exclude sudo, it runs successfully

**Comment by giovino** [comment]
given your next issue, I am going to assume you got past this one, closing.
