### ISSUE TITLE
inverse tag query

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/massive-octo-spice#254]
ability to do:

--tags botnet --not-tags dns,smtp,facilitator

**Comment by jgedeon120** [comment]
This would be great to have and would help quite a bit.

On Sat, Jun 27, 2015 at 9:55 AM, Wes <notifications@github.com> wrote:

> ability to do:
>
> --tags botnet --not-tags dns,smtp,facilitator
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csirtgadgets/massive-octo-spice/issues/254>.
>



-- 
Registered Linux User # 379282

**Comment by wesyoung** [comment]
i think this is gonna be a v3 thing...

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/bearded-avenger/issues/13

(short of a PR here)
