### ISSUE TITLE
feed parsing (goback)

### ISSUE THREAD

**Issue by villain** [csirtgadgets/massive-octo-spice#260]
not really an issue, but is there a v1 'goback' field equivalent in v2?

some of the (vendor) feeds i ingest arent so timely with releasing their data and have the original date of the event in the field, not the date they're reporting it to me. sometime this event can be a few months back. in v1 i was using the goback field to catch this, but i cant see anything similar in the v2 doc

**Comment by wesyoung** [comment]
yes, in cif-smrt checkout the `--not-before` flag:

```
 --not-before=STRING     specify a time to begin processing the data "[today|yesterday|X days ago]"
```

let me know if that helps.

**Comment by villain** [comment]
can you set that in a config file?

**Comment by giovino** [comment]
@villain you'll be able to in cif-beta-13 (https://github.com/csirtgadgets/massive-octo-spice/commit/a887fe7039d3007576116f0169a0c088736ae6bd)

something like

sudo vim /etc/cif/cif-smrt.yml
```+ $notbefore = "3 days ago"```

in cif-beta-12 or lower it's probably easiest to edit /opt/cif/bin/cif-smrt:

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/src/bin/cif-smrt#L31
