### ISSUE TITLE
zeustracker

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/massive-octo-spice#264]
```
[2015-07-02T10:23:37,462Z][INFO]: processing: -r /etc/cif/rules/default/zeustracker.yml -f binaries
[2015-07-02T10:23:38,505Z][ERROR]: not a well formed RSS document from: https://zeustracker.abuse.ch/monitor.php?urlfeed=binaries
[2015-07-02T10:23:38,505Z][ERROR]: skipping...
[2015-07-02T10:23:38,804Z][INFO]: processed events: 0
[2015-07-02T10:23:38,804Z][INFO]: nothing new to send...
[2015-07-02T10:23:38,804Z][INFO]: processing: -r /etc/cif/rules/default/zeustracker.yml -f configs
[2015-07-02T10:23:39,642Z][ERROR]: not a well formed RSS document from: https://zeustracker.abuse.ch/monitor.php?urlfeed=configs
[2015-07-02T10:23:39,642Z][ERROR]: skipping...
```

**Comment by jgedeon120** [comment]
I'm working on redoing all our rule config files.  When I get to this one I will send you what I have working, should be today or tomorrow.

**Comment by wesyoung** [comment]
rock on!

**Comment by jgedeon120** [comment]
I did not get this finished this weekend I was running into YAML::Tiny
issues trying to change the pattern it seem not all the feeds have the same
pattern.  Mainly version is not in all of them.

On Mon, Jul 6, 2015 at 7:37 AM, Wes <notifications@github.com> wrote:

> rock on!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csirtgadgets/massive-octo-spice/issues/264#issuecomment-118827995>
> .
>



-- 
Registered Linux User # 379282

**Comment by wesyoung** [comment]
sOk, if you get stuck, dump what you have and we can try to help you through it...

**Comment by jgedeon120** [comment]
Working through it now.  Adding a little to it now, wanted to get the MD5
hashes in also.  Should be able to send something to you later today.

On Mon, Jul 6, 2015 at 12:11 PM, Wes <notifications@github.com> wrote:

> sOk, if you get stuck, dump what you have and we can try to help you
> through it...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csirtgadgets/massive-octo-spice/issues/264#issuecomment-118912050>
> .
>



-- 
Registered Linux User # 379282

**Comment by jgedeon120** [comment]
Wes this is what we have working now as expected.

https://gist.github.com/7dfac603bde8f4c33ea5.git

**Comment by giovino** [comment]
working link to jgedeon120's gist contribution:

https://gist.github.com/jgedeon120/7dfac603bde8f4c33ea5

**Comment by wesyoung** [comment]
so, are we saying the config works? can we just turn that into a PR ?

**Comment by jgedeon120** [comment]
DIJ, aka da.. it joe.  Thanks for fixing it.  This was working as expected
all weekend.  We did chance it to not care if the url was online or
offline.  We still wanted the data.

On Wed, Jul 8, 2015 at 7:32 AM, Gabriel Iovino <notifications@github.com>
wrote:

> working link to jgedeon120's gist contribution:
>
> https://gist.github.com/jgedeon120/7dfac603bde8f4c33ea5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csirtgadgets/massive-octo-spice/issues/264#issuecomment-119546270>
> .
>



-- 
Registered Linux User # 379282
