### ISSUE TITLE
Duplicate feeds

### ISSUE THREAD

**Issue by jgedeon120** [csirtgadgets/massive-octo-spice#265]
It seems that openbl and sshbl are duplicates.  The remote URL is a little different but they are files that are being pulled down and processed.

227546fc5c4094fb60d2485543ce21db  openbl_base_1days.txt
227546fc5c4094fb60d2485543ce21db  sshbl_base_1days.txt

**Comment by giovino** [comment]
Good catch, I've made a pull request to have sshbl.yml remove. https://github.com/giovino/massive-octo-spice/commit/4f88a74143c0b7475b153b8985bb2d7a758c123e
