### ISSUE TITLE
Create provider profiles

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#274]
Create profiles for data providers:

* URL
* Short description of who they are:
* Short description of what the data is:
* Screenshot of data before (raw) and data after (normalized)
* config

first five:
1. Spamhaus
2. DRG
3. Phishtank
4. Malware domains

**Comment by giovino** [comment]
@wesyoung 

First attempt using DRG as the source:

https://github.com/csirtgadgets/CIF-Data-Providers/wiki/Dragon-Research-Group

add/remove/change?

**Comment by wesyoung** [comment]
i like it!

**Comment by giovino** [comment]
First iteration of this has been completed. 

https://github.com/csirtgadgets/CIF-Data-Providers/wiki
