### ISSUE TITLE
Feed location setting

### ISSUE THREAD

**Issue by jgedeon120** [csirtgadgets/massive-octo-spice#277]
Would it be possible in /etc/default/cif to set or create a variable that if set would change the location for cif-smrt to process the feeds from.  Being able to set a secondary location via this method would make it so that source code would not need to be edit.  This would also assist in feeds being customized not being overwritten during upgrades.

**Comment by giovino** [comment]
It looks like the thought is there but I'm not sure this can actually be invoked.

https://github.com/csirtgadgets/massive-octo-spice/blob/e87abf53461bceb70bdcbb8caa56edfad7f007c5/src/lib/CIF/Generated.pm.in#L36

**Comment by wesyoung** [comment]
i think it'd just require submitting a PR around this:

https://github.com/csirtgadgets/massive-octo-spice/blob/e87abf53461bceb70bdcbb8caa56edfad7f007c5/hacking/packaging/ubuntu/init.d/cif-smrt#L50

where you specify -r using a var from /etc/default/cif-smrt

something like:

[/etc/default/cif-smrt]
```
RULES_DIR=/etc/cif/rules/local
```

init.d/cif-smrt
```
DAEMON_OPTS="$CIF_DEBUGGING --logging --logfile $LOG_FILE -p $PID_FILE -C $CONF_FILE -r $RULES_DIR -D start"
```

but make sure that `/etc/cif/rules/default` is specified as the default in init.d/cif-smrt and `/etc/default/cif-smrt` overrides that if it exists... 

make sense?
