### ISSUE TITLE
cif does not appear to include MD5 hashes from default rules, and cif --otype hash does not seem to work

### ISSUE THREAD

**Issue by keithjjones** [csirtgadgets/massive-octo-spice#281]
Version:  2.00.00-beta.11 2015-07-06

I am using the default set of rules.  I ran cif-smrt in testmode and cif-smrt in daemon mode to pull all of the data since yesterday.  There appears to be hashes in the data:

```
root@cif-virtual-machine:/var/smrt/cache# head -n 15 /var/smrt/cache/malc0de.com-urls 
<?xml version='1.0' encoding='ISO-8859-1'?>
<rss version='2.0'>
<channel>
<title>Malc0de Database Feed</title>
<link>http://malc0de.com/database/</link>
<description>Updated Feed of Malicious Executables</description>
<language>en-us</language>
<copyright>Copyright (C) 2010 malc0de.com</copyright>
<item>
<title>117.21.175.128</title>
<link>http://malc0de.com/database/index.php?search=117.21.175.128</link>
<description>URL: 117.21.175.128/and40a361.exe, IP Address: 117.21.175.128, Country: CN, ASN: 4134, MD5: 9017029e8ffe5d0694b95b978f953ff3</description>
</item>
<item>
```

I query for the MD5 hash observed above:

```
root@cif-virtual-machine:~# cif -q 9017029e8ffe5d0694b95b978f953ff3
tlp  |group   |reporttime          |observable                      |cc|asn|confidence|tags  |description|rdata|provider      |altid_tlp|altid
amber|everyone|2015-07-09T14:20:26Z|9017029e8ffe5d0694b95b978f953ff3|  |   |25        |search|           |     |root@localhost|         |     
amber|everyone|2015-07-09T14:21:47Z|9017029e8ffe5d0694b95b978f953ff3|  |   |25        |search|           |     |root@localhost|         |     
amber|everyone|2015-07-09T14:21:55Z|9017029e8ffe5d0694b95b978f953ff3|  |   |25        |search|           |     |root@localhost|         |     
amber|everyone|2015-07-09T14:21:58Z|9017029e8ffe5d0694b95b978f953ff3|  |   |25        |search|           |     |root@localhost|         |     
amber|everyone|2015-07-09T14:22:06Z|9017029e8ffe5d0694b95b978f953ff3|  |   |25        |search|           |     |root@localhost|         |
```

Note that the output only includes my previous searches.  It does not show the hash found in the input data.  I believe other inputs than "malc0de.com-urls" have MD5 hashes as well.  I didn't make an exhaustive list.

I try to list all of the hashes, which I believe should show my searches and any other MD5 hashes:

```
root@cif-virtual-machine:~# cif --otype hash
root@cif-virtual-machine:~# 
```

The output is empty.  I think there are two issues:

1) All of the default inputs (rules) may not be parsed for hashes.  
2) The "cif --otype hash" command may not be working correctly.

I've tried all of the testing I could to see if these are issues.  Please let me know if there is additional testing I could do for you.

**Comment by giovino** [comment]
1) It would appear we have commented out the parsing of MD5 hashes malc0de.com config[1]. I do not know the reason why. Wes do you recall?

[1] https://github.com/csirtgadgets/massive-octo-spice/blob/develop/src/rules/default/malc0de.yml

2) It's not clear to me that you can even call cif --otype hash... @wesyoung ?

Thanks for the detailed question, it made it easy to answer even if the answers might be a little stinky.

**Comment by wesyoung** [comment]
i haven't really done a whole lot of testing of the hash otype specifically, so might just be a few small quick fixes. as for:

https://github.com/csirtgadgets/massive-octo-spice/commit/1cdc21b52e2332dd6aa80b62696be8517c91d4d0#diff-03b59e6f463c2bd016a8c42c2b2885da

my guess is, something was borked when we brought it over, just commented out the bad bits and moved on. i wanna say something was messed up with the feed at the time, or wasn't sure how to handle it... 

probably just a "got distracted" and now we need to spend some cycles working through it.

**Comment by giovino** [comment]
I'll turn these into two separate issues to be investigated. thanks... closing.
