### ISSUE TITLE
cif --otype hash

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#284]
Is ```cif --otype hash``` a supported query? If so, it appears to be broken as it returns zero results:

```
cif -q 1d6b6215ee7f3657a766403793b17d42 -f csvtlp,group,reporttime,observable,cc,asn,confidence,tags,description,rdata,provider,altid_tlp,altid
amber,everyone,2015-07-09T16:51:20Z,1d6b6215ee7f3657a766403793b17d42,,,85,malware,,,me.com,,
amber,everyone,2015-07-09T16:51:34Z,1d6b6215ee7f3657a766403793b17d42,,,25,search,,,root@localhost,,
```

```
cif -v --otype hash -c 25
[2015-07-09T16:52:52,564Z][INFO]: starting up client...
[2015-07-09T16:52:52,565Z][INFO]: running search...
[2015-07-09T16:52:53,087Z][INFO]: status: 200
[2015-07-09T16:52:53,087Z][INFO]: no results found...
```

**Comment by wesyoung** [comment]
see:

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/src/lib/CIF/Plugin/Hash.pm

i think we went this time with specific values...

**Comment by keithjjones** [comment]
This may address a similar issue?

https://github.com/csirtgadgets/p5-cif-sdk/issues/28

**Comment by keithjjones** [comment]
How are you using cif with the "-f" option above?  It appears as if "-f" is supposed to represent the output format, not the columns.  I cannot find a way to print out the columns in CIF v2.  It looks like you used a CIF v1 command on the first line.

**Comment by giovino** [comment]
The CIF client in CIFv2 does _NOT_ have the following option/feature which can be found in CIFv1:

```-f  --fields:           set default output fields for default table display```

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/p5-cif-sdk/issues/42

**Comment by wesyoung** [comment]
--fields in master.
