### ISSUE TITLE
Problem with URL/IP inactive

### ISSUE THREAD

**Issue by perez1987** [csirtgadgets/massive-octo-spice#289]
Good Morning,

When you import a new feed CIF url/ips which are not active not insert to the database. How could disable such a check? I want to add to the database all, without exception.

Thank you very much!

**Comment by giovino** [comment]
Can you define "not active"? Sample data might help.

**Comment by perez1987** [comment]
I not understand .. Can you explain me? I need cif inserted into database all URLs from a feed, whether active or not.

**Comment by giovino** [comment]
CIF doesn't know if a URL is "active" or not. What CIF _may_ know (if specified) is the last time the URL was "last seen". 

Let me give you two examples:

URL feed 1:

```
URL,Timestamp,Description
http://www.example.com,2015-07-15T00:00:00Z,malicious
```

URL feed 2:

```
URL,Description
http://example.com,malicious
```

In "URL feed 1", we are able to tell CIF when the URL was "last seen" as a timestamp is given. In "URL feed 2". 

Are you ingesting URL data with a timestamp similar to "URL feed 1"?

**Comment by perez1987** [comment]
Of the two types @giovino 

And what parameters CIF consider to add a URL or not from a feed?

Because there are URLs not added to the database

Thank you very much

**Comment by perez1987** [comment]
@giovino For example,

I just create me a feed in local these 4 URL:
14501.netpro99.hop.clickbank.net
14dayrapidfatlossplan.com
14dayseczemacure.com
testfrommylocal.com

The first 3 if inserted in database but the last one is a test not inserted. Why?

**Comment by giovino** [comment]
I cannot duplicate what you are experiencing. 

Example feed config:

```
$ cat csv_example.yml 

parser: csv
defaults:
  provider: feeds.example.com
  altid_tlp: amber
  tlp: amber
  confidence: 75
  values:
    - observable
feeds:
  csv_example:
    remote: /home/<user>/data.csv
    tags: botnet
```

Example feed file:
```
$ cat data.csv

14501.netpro99.hop.clickbank.net
14dayrapidfatlossplan.com
14dayseczemacure.com
testfrommylocal.com
```

Sample command to get CIF to parse the feed file:
```
$ sudo su - cif -c "/opt/cif/bin/cif-smrt --testmode -c -d -r /home/<user>/csv_example.yml"
```

testfrommylocal.com seen in CIF:
```
$ cif -q testfrommylocal.com
tlp  |group   |reporttime          |observable         |cc|asn|confidence|tags  |description|rdata|provider         |altid_tlp|altid                 
amber|everyone|2015-07-16T11:15:35Z|testfrommylocal.com|  |   |75        |botnet|           |     |feeds.example.com|amber    |/home/<user>/data.csv
```

**Comment by perez1987** [comment]
Thank you very much! I will continue testing because  the other day not inserted into database.

Thank You !!!!!!

**Comment by giovino** [comment]
Closing for now.
