### ISSUE TITLE
update bind wiki doc

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#290]
update the bind doc to reflect --feed

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/wiki/Bind/_compare/70ab88d37b6b1e037c7885a621477a4c7a15cd4a...e91aa39be50681a2db1e6a7097969b957b625a0f

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/wiki/Bind/_compare/70ab88d37b6b1e037c7885a621477a4c7a15cd4a...dd4ef5e6138e672b9e482b06448dd7d81d71369f

**Comment by giovino** [comment]
why not --feed?

**Comment by giovino** [comment]
doesn't it need ```-f bind``` too?

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/wiki/Bind

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/wiki/Bind/_compare/70ab88d37b6b1e037c7885a621477a4c7a15cd4a...432593a45245893537d54af19d0c7b986ae3c67b
