### ISSUE TITLE
Update DateTime.pm to support (dd-mm-yyyy)

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#295]
patch https://github.com/csirtgadgets/massive-octo-spice/blob/develop/src/lib/CIF/Plugin/DateTime.pm (with a test) to support that date format

Reference:
https://github.com/csirtgadgets/bearded-avenger/issues/10#issuecomment-123739321

**Comment by wesyoung** [comment]
https://en.wikipedia.org/wiki/Date_format_by_country

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/commit/fd7b49983b992ea954efb175a2c934dd31d620e5
