### ISSUE TITLE
Relationship between observable and rdata field

### ISSUE THREAD

**Issue by perez1987** [csirtgadgets/massive-octo-spice#296]
I have mounted CIF system. I have two questions:

- How do you relationship between observable and rdata fields? Eg if I have an event of threat and contain a URI, IPV4 and MD5 ... how is the relationship?

- What algorithm is based CIFto calculate the confidence? Is it based on the time tag, provider ...?

Thank you

**Comment by giovino** [comment]
Q1: rdata is typically available when CIF post processes data ingested in CIF. Examples:

 - observable: http://www.example.com -> rdata: example.com
 - observable: example.com -> rdata: 1.1.1.1

example.com is related (rdata) to http://www.example.com
1.1.1.1 is related (rdata) to example.com

rdata is normally populated by CIF processors but there is no reason you couldn't populate rdata using cif-smrt or the CIF API. 

Q2: Confidence is specified by the admin on ingest. For OSINT feeds that ship with the CIF project the CIF projects sets a value that we think make sense following these general rules: (https://github.com/csirtgadgets/massive-octo-spice/wiki/Confidence). 

For rdata, the algorithm that computes the confidence score is:

initial_confidence * (log(initial_confidence) / log(500))

https://github.com/csirtgadgets/massive-octo-spice/blob/e87abf53461bceb70bdcbb8caa56edfad7f007c5/src/lib/CIF/WorkerRole.pm#L5

**Comment by perez1987** [comment]
One question.. what is "log"?

**Comment by giovino** [comment]
@perez1987 

http://perldoc.perl.org/functions/log.html
https://www.mathsisfun.com/algebra/logarithms.html
https://en.wikipedia.org/wiki/Logarithm
