### ISSUE TITLE
default tlp from amber to green

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/massive-octo-spice#303]

**Comment by giovino** [comment]
Are you sure the public feeds shouldn't be TLP: White?

Reference:
https://www.us-cert.gov/tlp
https://en.wikipedia.org/wiki/Traffic_Light_Protocol
https://www.cert.be/traffic-light-protocol-tlp

**Comment by wesyoung** [comment]
i think this gets into "what you want a community to respect" in terms of sharing data and sharing attribution.

ex:

data point comes in tlp green under groupA and the altid is white, does that mean "you can share the reference this came in under white, but the fact that groupA knows about this, as 'green'"  .. i think?
