### ISSUE TITLE
installer: add framework for centos

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#324]

**Comment by giovino** [comment]
Ansible has been prototyped for the installation and configuration of cifv2. You can see that work here:

https://github.com/csirtgadgets/massive-octo-spice/tree/develop/ansible

It's probably easier to leverage Ansible opposed to writing more shell scripts. See the README in develop/ansible for more information.

**Comment by wesyoung** [comment]
if we just straight up finish dockerizing this and push to dockerhub does that "solve" this?
