### ISSUE TITLE
What is the scalability of CIF?

### ISSUE THREAD

**Issue by perez1987** [csirtgadgets/massive-octo-spice#331]
Hi,

I know that scalability is CIF. I worry that CIFA is not a very scalable system.

**Comment by wesyoung** [comment]
do you have a specific piece of the infrastructure you're concerned about? (ie: database, messaging, etc...?) or a scenario you're trying to get help with?

**Comment by perez1987** [comment]
@wesyoung 

We seek to have an infrastructure that is no problem to grow.

Eg elastic search is scalable because you mount a cluster, you add nodes elasticsearch and can grow whatever you want ...

How scalable is CIF in that sense?

**Comment by wesyoung** [comment]
it just uses ES on the backend, so however you end up scaling out ES, the REST api's (http front end to CIF) just points at that. if you have heavy front end loads to the HTTP interface, you just scale that sideways and point them at your ES cluster too.

**Comment by perez1987** [comment]
Sorry but I just do not understand :-(

On the one hand I understand that we have is just the backend, so that part of scalability we have it covered.

On the other charging processes by example import of feeds I do not know how to cover that part scalability

If you can explain it again ...

Thank you @wesyoung

**Comment by wesyoung** [comment]
the term "scalability" is sort of an overly broad question, which can apply to many different pieces in many different ways. can you give me an example scenario that you're concerned about? most of the feed processing limitations come down to memory and cores, and then scaling those pieces out (ie: splitting out elastic-search, splitting out cif-workers to a diff box, etc).

have you started testing a v2 instance yet? that might be your best bet in determining where your concerns might be...

**Comment by perez1987** [comment]
I explain @wesyoung :

Now have a CIF v2 server deployed with a cluster of elastic search. The scalability of ES are cover.

I want to know if CIF is scalable vertically, that is, if I deploy N machines with the CIF service and the work is distributed, all operating under docker.
I think that having a high need for such resources is not scalable in that regard, and we are concerned that we can not grow in that direction.

**Comment by wesyoung** [comment]
in this case, if you were spin up "cif-router" boxes that all pointed to an ES backend, and load-balanced the front end (round robin, an actual load balancer) then yes. the only thing you'd then have to do is make sure to turn-down cif-smrt on the cif-router boxes, install cif-smrt to a single external box and point it at your load balanced CNAME.

something like:

https://docs.google.com/drawings/d/14nDXIKVVowcsjRx5GtQyl_dqxdhNM7btSq1qoEtOmA8/edit

that being said, i'm still working on some of the "config / ease of use" bits myself for an internal deployment now that most of the bugs are ironed out, so there might be some quirks along the way that we're ironing out. but that's the config i'm working with currently...

**Comment by perez1987** [comment]
Right @wesyoung 

The load of CIF-SMRT can be scaled to a load balancer. But .. and the whole load of the CIF-WORKER as you can make scalability?

Thanks!

**Comment by wesyoung** [comment]
right now, cif-worker hangs off of a zeromq PUB/SUB pipe, and while technically it was built with that sideways scaling in mind, i'm not sure the configurability is there just yet... i'm not so sure it's a technical issue is making it more configurable... 

see:

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/src/bin/cif-worker#L86
https://github.com/csirtgadgets/massive-octo-spice/blob/develop/src/lib/CIF/Router.pm#L152

by scaling out the cif-router/cif-workers together, you scale both the workers and the "pre-processing" that goes into play when adding ASN, BGP and CountryCode data too... (there are other processes in play besides cif-worker)

**Comment by perez1987** [comment]
I just do not understand very well what "remote publisher" @wesyoung 

Within "--publisher = STRING" indicate all servers with the CIF-worker process running, right?

No, I just knew we would do well as the scalability of all these processes .. (CIF-worker, CIF-router ...)

**Comment by perez1987** [comment]
So I could review could also give scalability to process CIF-router and CIF-work using a load balancer. The process uses ports 4961 and 4963, would aim localhost:4961 and localhost:4963 into a load balancer.

What do you think @wesyoung @giovino ?

**Comment by wesyoung** [comment]
@perez1987 have you spent any time with ZeroMQ?

http://zeromq.org/intro:read-the-manual

if you spend some time learning that, the rest of the CIF "interconnects" might make a little more sense...

**Comment by perez1987** [comment]
Thanks for everything @wesyoung . When we get to the scalability of CIF give you feedback.
