### ISSUE TITLE
weekly cif-worker cron

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#332]
I believe the weekly cif-worker restart cron is leaving threads open. 

```/etc/init.d/cif-worker restart > /dev/null 2>&1```

Can duplicate with the following:

1. ```ps aux | grep ^cif | grep cif-worker | wc -l```
1. ```sudo /etc/init.d/cif-worker restart > /dev/null 2>&1```
1. ```ps aux | grep ^cif | grep cif-worker | wc -l```

**Comment by wesyoung** [comment]
merge this with #322 (have a branch for that..)

**Comment by giovino** [comment]
for ```service cif-worker restart``` or ```service cif-worker stop``` does there need to be a PID for every thread started?

I see one PID:

```cat cif-worker.pid 
11946```

**Comment by wesyoung** [comment]
no, we only keep track of the master pid there (which controls all the threads and their PIDs internally..).

**Comment by giovino** [comment]
being addressed in this patch https://github.com/csirtgadgets/massive-octo-spice/commit/67c248b080fa7e380c09557cb45b9e2b24a85553

closing
