### ISSUE TITLE
Is the parameter 'period' supported in cif-smrt?

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#337]
We have the 'period' parameter referenced [here](https://github.com/csirtgadgets/massive-octo-spice/wiki/ParsingFeeds#all-parameters) which is probably sourced from [here](https://github.com/csirtgadgets/massive-octo-spice/blob/fae13c3b9a9aea2a6b662795d9b8de51c5356cc2/src/rules/example/pastebin.yml)

I suspect that this is carried over from v1 but is not really a valid parameter for cif-smrt in cifv2. 

Wes can you confirm? If so we can remove it from the wiki and the example pastebin.yml file.

**Comment by wesyoung** [comment]
it can be removed. since we're keeping track of what we've submitted (each day) via the journal, the period doesn't apply anymore...
