### ISSUE TITLE
look at geolocation data in ES

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#344]
Should the geolocation data in ES be typed at geo_point vs a string? Question asked by Cacheburn in cif irc channel. 

Geo Point Type
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html

This would allow "tile maps" to work in Kibana4, in Kibana3 "tile maps" used country code.

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/blob/develop/elasticsearch/observables.json#L58

**Comment by wesyoung** [comment]
maybe they're using a pre-beta.14 version?

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/commit/6dac80e49f4f2515abe3db36e2bf3bfe657cafe7#diff-eb36386e7c8a0e19ca5021e929b45668

**Comment by rhelfter** [comment]
I have the latest version.  This is an install from 2 days ago.

Can anyone paste their ES output for the geolocation field so I may compare?

"http://localhost:9200/cif*/_mapping/field/geolocation?pretty"

  "cif.observables-2015.09.14" : {
    "mappings" : {
      "observables" : {
        "geolocation" : {
          "full_name" : "geolocation",
          "mapping" : {
            "geolocation" : {
              "type" : "string",
              "norms" : {
                "enabled" : false
              },
              "fields" : {
                "raw" : {
                  "type" : "string",
                  "index" : "not_analyzed",
                  "ignore_above" : 256
                }
              }
            }
          }
        }
      }
    }
  }

**Comment by giovino** [comment]
Here's my output:

```
curl http://localhost:9200/cif.observables-2015.09.09/_mapping/field/geolocation?pretty
{
  "cif.observables-2015.09.09" : {
    "mappings" : {
      "observables" : {
        "geolocation" : {
          "full_name" : "geolocation",
          "mapping":{"geolocation":{"type":"geo_point"}}
        }
      }
    }
  }
}
```

**Comment by giovino** [comment]
We learned that ```elasticsearch/Makefile.am``` failed because ES was not on the local host. The installer was performed manually.
