### ISSUE TITLE
portlist missing in api doc

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#356]
Should portlist be in this doc?

https://github.com/csirtgadgets/massive-octo-spice/wiki/API

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/wiki/API/_compare/74f510a892bf4812793587ac9f8e2ee2bedfa29e...4f061c79072ac0d6b1def24124e647cb52de0c0b
