### ISSUE TITLE
py-cifsdk filter for Cryptowall

### ISSUE THREAD

**Issue by evrenbey** [csirtgadgets/massive-octo-spice#361]
Hello

i installed py-cifsdk and as i see there are no parameters like --description and --last-day.

i used it at the CIF server and i got only last day Cryptowall data with command below

    CIF --description crytptowall --last-day

is there any way only pull last day  Cryptowall TI data with CIF client.

**Comment by giovino** [comment]
1. I have created two issues documenting the missing arguments in py-cifsdk

https://github.com/csirtgadgets/py-cifsdk/issues/32
https://github.com/csirtgadgets/py-cifsdk/issues/33

2. I think you could hack around this for the time being with some bash-fu:

https://gist.github.com/giovino/63e123b0dd1e1afe3b2f

Thanks!

**Comment by wesyoung** [comment]
fwiw, the py-cifsdk lags the p5-cifsdk as far as feature parity atm, but it's on my short list of things to finish in the next week or two.. (similar with the --feed command, solving some ipv6 issues...)

**Comment by wesyoung** [comment]
(closing since we're keeping track in the py-cifsdk repo...)
