### ISSUE TITLE
Kibana installation problem :(

### ISSUE THREAD

**Issue by evrenbey** [csirtgadgets/massive-octo-spice#366]
Hello

i read the KibanaGuide so many times and try much more times,

but couldnt run Kibana.

Kibana welcome screen  doesnt seen.

is there anybody who can managed working Kibana ?

**Comment by giovino** [comment]
This is a better question for the cif users group. You can see other Kibana threads here:

https://groups.google.com/forum/#!searchin/ci-framework/kibana

I am going to close this issue as it is not an issue directly related to CIF. Thanks!
