### ISSUE TITLE
refactor remote=localhost:9200

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#371]
Need to make remote a variable in the following locations:

1. https://github.com/csirtgadgets/massive-octo-spice/blob/f01b0c676f653b30713dc0618324a69dd360c081/src/bin/cif-router

2. https://github.com/csirtgadgets/massive-octo-spice/blob/f01b0c676f653b30713dc0618324a69dd360c081/src/bin/cif-tokens

3. https://github.com/csirtgadgets/massive-octo-spice/blob/ab7c517e0a90e8f25b346180cc6d04c59b072e15/src/lib/CIF/Storage/ElasticSearch.pm

**Comment by wesyoung** [comment]
4439d1016bf587e1e734cf5b7e4af387431c68de
