### ISSUE TITLE
worker never stops trying to connect to router

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#373]
in this [loop](https://github.com/csirtgadgets/massive-octo-spice/blob/f01b0c676f653b30713dc0618324a69dd360c081/src/bin/cif-worker#L158) cif-worker will try to connect to the router indefinitely, if the router is not available, starting / restarting cif-worker hangs: 

```bash
$ sudo service cif-services restart
 * Stopping cif-router                                                                                                                                                             [ OK ] 
 * Starting cif-router                                                                                                                                                             [ OK ] 
 * Stopping cif-worker                                                                                                                                                             [ OK ] 
 * Starting cif-worker               
```

potential fix: add a counter and after 8 tries (15s x 8 = 120s) fail with message "cif-router is unavailable"

**Comment by giovino** [comment]
this probably gets more complicated as monit will restart the service

**Comment by wesyoung** [comment]
ironically i ran into this one this am.. i think it should start and loop, just not hang...? or quit after a few attempts... i'm kinda in-different, but given the way monit is configured... the loop doesn't hurt does it?

**Comment by giovino** [comment]
I think the "hurt" is.. service cif-worker start/restart.. hangs forever when it can't complete. The user is forced to ctrl-c to stop the init process. seems wonky.

**Comment by wesyoung** [comment]
given what i exp this am, i think that's fair. probably as easy as adding a similar first-check loop to cif-router as we did with cif-worker, then adding a limit and some output error info too.
