### ISSUE TITLE
Unknown option: days

### ISSUE THREAD

**Issue by villain** [csirtgadgets/massive-octo-spice#385]
when running a cif query and using --days X, i'm getting an error which says whats in the title

cif --otype fqdn --days 30 --tags x,y,z --feed --format bro

ive tried the --days at different positions in the command and all produce the same error

**Comment by wesyoung** [comment]
i think you might be running an older version of p5-cifsdk:

https://github.com/csirtgadgets/p5-cif-sdk/pull/51/files#diff-d0d0857688afde505586bea650adf5f6R100

try this:

```
$ sudo cpanm https://github.com/csirtgadgets/p5-cif-sdk/archive/2.00_33.tar.gz
```

**Comment by wesyoung** [comment]
if you still have issues we can re-open here:

https://github.com/csirtgadgets/p5-cif-sdk/issues/new
