### ISSUE TITLE
CIF Local Feeds

### ISSUE THREAD

**Issue by smtszk** [csirtgadgets/massive-octo-spice#390]
I created a feed configuration file to add new threat intelligence feeds, i wrote regex patterns and it works well. But I want to add more  malware IPs and urls. I have some text files, how can I export them to CIF?  Is there a local storage in CIF?

**Comment by giovino** [comment]
You can put a local file path in the "remote" key within a cif-smrt config file. [example](https://github.com/csirtgadgets/massive-octo-spice/blob/f01b0c676f653b30713dc0618324a69dd360c081/src/rules/default/00_whitelist.yml)

Process:

1. Write a [cif-smrt config file](https://github.com/csirtgadgets/massive-octo-spice/wiki/Parsing-Feeds-Tutorial) (file.yml) to parse the data in the local text file

2. Do not put the config file into /etc/cif/rules/default _unless_ this local text file will be updated hourly/daily by another process. 

3. Manually process the text file with a command something similar to this:

```sudo su - cif -c "/opt/cif/bin/cif-smrt -c -d -r /home/user/file.yml"```

Does this answer your questions?

**Comment by smtszk** [comment]
Yeah, this is totally what I want to hear. Thank you.

**Comment by giovino** [comment]
yw
