### ISSUE TITLE
adding user to a single group?

### ISSUE THREAD

**Issue by villain** [csirtgadgets/massive-octo-spice#408]
for reference, the doc ive been using is; https://github.com/csirtgadgets/massive-octo-spice/wiki/CIF-Groups

is it possible to add a user to a single group only, and not the everyone group? using cif-token, the new user is added to the new group and the everyone group;

cif@cif:~$ cif-tokens --new --user api-user --groups groupA --read
username            description groups              admin read write acl expires revoked token                                                           
api-user             groupA,everyone       yes                            23da1b48e39e7f4241b1d5878f5497038a2120ab5705781ae8c1b6c86cab00f8

i would like to give a user access to one source/provider only and nothing else (eg: not have access to the everyone group). if there's a simpler way to do this then i would love to hear that also

**Comment by coonsmatthew** [comment]
I've raised this question here: 
https://groups.google.com/forum/#!topic/ci-framework/2D5ksvf8QF0

And it is fixed in this commit: 
https://github.com/csirtgadgets/massive-octo-spice/pull/404

**Comment by villain** [comment]
excellent!
