### ISSUE TITLE
timeout when querying for ip address

### ISSUE THREAD

**Issue by villain** [csirtgadgets/massive-octo-spice#409]
a couple of users have mentioned this on the IRC channel, i figured i would drop by notes here to see if this solves anyone elses problem. if you have a large number of indexes (eg; from when it was daily indexes), you might be experiencing issues querying for an IP address which look something like:

cif@cif:~$ cif -q 1.2.3.4
<!DOCTYPE html>
<html>
  <head><title>Server error</title></head>
  <style>
      body { background-color: #caecf6 }
      #raptor {
        background: url(/mojo/failraptor.png);
        height: 488px;
        left: 50%;
        margin-left: -371px;
        margin-top: -244px;
        position:absolute;
        top: 50%;
        width: 743px;
      }
    </style>
  <body><div id="raptor"></div></body>
</html>
 at /usr/local/bin/cif line 310.

the line number above seems to differ for people, but the error message is the same

you might also see something similar to the below in the /var/log/cif-starmon.log, although i'm not sure if its related yet:
[Tue May  3 22:07:15 2016] [error] Can't use string ("0") as a HASH ref while "strict refs" in use at /opt/cif/bin/../lib/perl5/CIF/Client.pm line 225.

ive found a workaround to at least get data returned for queries for ip addresses is to throw --ttl=0 on the end, eg; cif -q 1.2.3.4 --ttl=0

what i'm unsure about is why using the cif command line to query would time out, however querying directly in elasticsearch seems to come back almost instantly;

GET cif.observables-*/observables/_search
{
  "query" : {
    "term" : {
      "observable" : "1.2.3.4"
    }
  }

..

{
   "took": 612,
   "timed_out": false,
   "_shards": {
      "total": 504,
      "successful": 504,
      "failed": 0
   },

**Comment by villain** [comment]
probably should add; querying for other observables (domains, md5 etc) is fine

**Comment by giovino** [comment]
In 2.00.00-rc.13 there were several enhancements applied to address this issue. (https://github.com/csirtgadgets/massive-octo-spice/commit/1dafea3840beac59f1343ba4a7e732402e8aab89 https://github.com/csirtgadgets/massive-octo-spice/commit/1b0598827643306631f0dcf6bace7c0ca5996062 https://github.com/csirtgadgets/massive-octo-spice/commit/5f415069400010bc9f81a703f5c92aeebccf9c81)

Are you continuing to see this behavior at rc.13+

**Comment by villain** [comment]
just tried upgrading to rc.13+ and getting an install issue:

t/10-worker.t .......... 3/? 0 is not a valid PositiveInt

Trace begun at /usr/local/share/perl/5.18.2/GeoIP2/Types.pm line 244
GeoIP2::Types::_tc_fail(0, 'PositiveInt') called at (eval 1160) line 70
eval {...} at (eval 1160) line 59
GeoIP2::Record::Location::new(undef, 'longitude', -97.822, 'latitude', 37.751, 'accuracy_radius', 0, 'locales', 'ARRAY(0x52ec8b8)') called at /usr/local/share/perl/5.18.2/GeoIP2/Role/Model/Location.pm line 100
GeoIP2::Role::Model::Location::_build_record('GeoIP2::Model::Insights=HASH(0x373c708)', 'location', '_raw_location') called at (eval 1159) line 30
GeoIP2::Model::Insights::location('GeoIP2::Model::Insights=HASH(0x373c708)') called at /home/cif/massive-octo-spice/src/blib/lib/CIF/Meta/GeoIP.pm line 76
CIF::Meta::GeoIP::process('CIF::Meta::GeoIP=HASH(0x534fa78)', 'HASH(0x529c070)') called at /home/cif/massive-octo-spice/src/blib/lib/CIF/Worker.pm line 188
CIF::Worker::_process_metadata('CIF::Worker=HASH(0x1174320)', 'HASH(0x529c070)') called at /home/cif/massive-octo-spice/src/blib/lib/CIF/Worker.pm line 160
CIF::Worker::process('CIF::Worker=HASH(0x1174320)', '{"id":"5d37137277053d00c38b341025ea2cce26be918eb085070eb3144dcf545fa397","lang":"EN","otype":"fqdn","confidence":85,"observable":"example.com"}') called at t/10-worker.t line 28
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 3.
t/10-worker.t .......... Dubious, test returned 255 (wstat 65280, 0xff00)
All 3 subtests passed 
t/20-alexa.t ........... ok   
t/20-arborflux-xml.t ... ok   
t/20-bambenek.t ........ ok   
t/20-blocklist_dt.t .... ok   
t/20-drg.t ............. ok   
t/20-isc_sans_edu.t .... ok    
t/20-malc0de.t ......... ok    
t/20-malwaredomains.t .. ok    
t/20-mirc.t ............ ok   
t/20-observable.t ...... ok   
t/20-openbl.t .......... ok   
t/20-openphish.t ....... ok   
t/20-phishtank.t ....... ok   
t/20-ransomware.t ...... ok   
t/20-sslbl_abuse.t ..... ok   
t/20-zeustracker.t ..... ok   
t/50-router.t .......... 2/? # starting client
# starting router...
# waiting...
# running ping...
t/50-router.t .......... 4/? # killing router...
t/50-router.t .......... ok   
t/60-freeform.t ........ ok   
t/60-passivedns.t ...... ok   

Test Summary Report
-------------------
t/10-worker.t        (Wstat: 65280 Tests: 3 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=29, Tests=237, 30 wallclock secs ( 0.22 usr  0.06 sys + 26.73 cusr  2.36 csys = 29.37 CPU)
Result: FAIL
Failed 1/29 test programs. 0/237 subtests failed.
make[1]: *** [test_dynamic] Error 255
make[1]: Leaving directory `/home/cif/massive-octo-spice/src'
make: *** [test] Error 2

**Comment by villain** [comment]
i'm still on RC12, i'll close this and re-open if the problem still exists

**Comment by priyamalik** [comment]
I am also facing same error.
I have installed CIF at two system (1 at ubuntu and 2nd on ubuntu-server). On 1st one every thing is fine but ubuntu server is throwing this error.

I have added --ttl=0 at the end but still same issue.
