### ISSUE TITLE
Adding tokens with --no-everyone option does not work

### ISSUE THREAD

**Issue by coonsmatthew** [csirtgadgets/massive-octo-spice#425]
I just upgraded our dev CIF instance to RC.15, and just tried adding a new token with the --no-everyone option, which does not seem to work. 

Here's what I'm executing: 

`user@server:/$ /opt/cif/bin/cif-tokens --new --username testuser3 --read --groups MyAmazingGroup --no-everyone`

And Here's the output:

`username  description groups                  admin read write acl expires revoked token`                                                      
`testuser3             MyAmazingGroup,everyone       yes                            1234567890`

It seems like the `--no-everyone` option is not setting the correct option for new users. 

I tailed all of the CIF logs in `\var\log` and the elasticsearch log and I do not see any obvious errors.

**Comment by giovino** [comment]
this fix broke my fix. 

https://github.com/csirtgadgets/massive-octo-spice/commit/6b4eef3246f9184767b8b6683b644d7752e41a54#diff-bb3f1b031e54e5e4074bfa8b4fceb9e0
