### ISSUE TITLE
Easybutton install error

### ISSUE THREAD

**Issue by maha0098** [csirtgadgets/massive-octo-spice#428]
When entering the given install command for the Easybutton, I receive the following error:

"error: pathspec 'master' did not match any file(s) known to git."

If I change the URL directory to remove 'master' and use  "https://raw.githubusercontent.com/csirtgadgets/massive-octo-spice/hacking/platforms/easybutton_curl.sh", then I receive the following error:

"bash: line 1: Not: command not found"

I am using Ubuntu 14.0.4. Thanks in advance for any help!

If it matters, I am operating behind a proxy. I have adjusted the command to reflect the following overall:
"curl --cacert *cert location* -x *proxy address* -Ls https://raw.githubusercontent.com/csirtgadgets/massive-octo-spice/master/hacking/platforms/easybutton_curl.sh | sudo bash -"

**Comment by giovino** [comment]
I can verify that I just ran this script on a aws test instance and had no issues:

```curl -Ls https://raw.githubusercontent.com/csirtgadgets/massive-octo-spice/master/hacking/platforms/easybutton_curl.sh | sudo bash -```

I do not believe there is a bug in the script. 

It's extremely difficult for us to troubleshoot "easybutton" errors when you are behind a proxy. My suggestion would be to:

1. Test the install process in a virtual machine so you can easily snapshot and start over
1. Run through the install process semi-manually to see if you can get past any proxy errors:

Start here, perform lines roughly 35-43. 

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/hacking/platforms/easybutton_curl.sh#L35

Line 43 really kicks off ```easybutton.sh```

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/hacking/platforms/easybutton_curl.sh#L43

minus the little bit of testing, ```easybutton.sh``` really only kicks off  ```ubuntu.sh```

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/hacking/platforms/easybutton.sh#L52

A lot of software packages are downloaded in ```ubuntu.sh```. (e.g. there is a lot of opportunities for a proxy server to get in the way)

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/hacking/platforms/ubuntu/ubuntu.sh

I would debug this as a proxy server error unless you can prove it isn't. Hope this helps!

**Comment by wesyoung** [comment]
i'm actually pretty sure the easybutton is not very proxy friendly. it does a lot of different types of HTTP(S) calls out while it's installing different things (apt-get, cpanm, etc). if you do get through it, we'd be more than happy to accept a PR with what you find... :)

my first stab at this would be trying to toggle the env level proxy vars to see if the various tools pick it up correctly, past that it's probably a bit of trial and error...

**Comment by maha0098** [comment]
Thank you for the thorough explanation and assistance! If I am able to get it working from behind the proxy, I'll document my process here.

**Comment by wesyoung** [comment]
no prob. i'm gonna close this for now, we can re-open if you submit a PR. i've also logged:

https://github.com/csirtgadgets/bearded-avenger/issues/64

for the next version to make sure we try our best to account for proxies (just not something we've had the resources to solve).
