### ISSUE TITLE
csirtgadgets/massive-octo-spice.git - unable to access

### ISSUE THREAD

**Issue by tejusun65** [csirtgadgets/massive-octo-spice#431]
I tried to install CIFF server and gettng "fata:unable to access" when i run the easybutton_curl.sh script.   Has anybody encountered this error?

**Comment by wesyoung** [comment]
how are you executing the script and what does it give as output (context around that error)?

**Comment by tejusun65** [comment]
Executing the script using the command
curl -Ls https://raw.githubusercontent.com/csirtgadgets/massive-octo-spice/master/hacking/platforms/easybutton_curl.sh | sudo bash –

The output is:

“Hit http://us.archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://us.archive.ubuntu.com trusty Release
Hit http://us.archive.ubuntu.com trusty/main Sources
Hit http://us.archive.ubuntu.com trusty/restricted Sources
Hit http://us.archive.ubuntu.com trusty/universe Sources
Hit http://us.archive.ubuntu.com trusty/multiverse Sources
Hit http://us.archive.ubuntu.com trusty/main amd64 Packages
Hit http://us.archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://us.archive.ubuntu.com trusty/universe amd64 Packages
Hit http://us.archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://us.archive.ubuntu.com trusty/main i386 Packages
Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty/main Translation-en
Hit http://us.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty/universe Translation-en
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US
Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version.
automake is already the newest version.
build-essential is already the newest version.
htop is already the newest version.
git is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Cloning into 'massive-octo-spice'...
fatal: unable to access 'https://github.com/csirtgadgets/massive-octo-spice.git/  ': Failed to connect to github.com port 443: Connection timed out”

**Comment by wesyoung** [comment]
hrm, usually this is a connection issue with github itself, esp if the first part of that worked ok. (usually network glitch). or if you're behind a proxy, that could affect it too..

can you:

```
$ curl https://api.github.com/
```

if so, does re-running the easybutton work?

**Comment by tejusun65** [comment]
Yes, looks like we have a network glitch.  Thanks

**Comment by wesyoung** [comment]
Np! Good luck :)
