### ISSUE TITLE
Issue in CIF Sever instalation

### ISSUE THREAD

**Issue by diveshshah** [csirtgadgets/massive-octo-spice#436]
Dear All,

    We are facing issue while installing CIF server .

    curl -Ls https://raw.githubusercontent.com/csirtgadgets/massive-octo-spice/fix/399/hacking/platforms/easybutton_curl.sh | sudo bash -

    Issue--->Checking for an Internet connection
    http://github.com appears to be available via HTTP
    Currently only 14.04 LTS is supported
    We accept Pull Requests! =)
    chown: cannot access '/home/ubuntu/.cif.yml': No such file or directory

    Kindly help us to resolve this issue.

    Thanks & Regards
    Divesh Shah

**Comment by wesyoung** [comment]
currently only ubuntu1404 is supported (as per the error message). what OS are you trying to install this on?

**Comment by diveshshah** [comment]
Thanks for informing. 

We were using ubuntu16 that time(yesterday) .but today we changed to ubuntu 14. 
So now its install. 

Thanks & Regards 
Divesh Shah

**Comment by diveshshah** [comment]
Please close this issue
