### ISSUE TITLE
Missing ./configure file

### ISSUE THREAD

**Issue by bekoons** [csirtgadgets/massive-octo-spice#442]
Running /hacking/platforms/./easybutton.sh results in "./ubuntu.sh: line 98: ./configure: No such file or directory." Browsing the directories in the git repo I don't see any file called "configure.sh" even though it is referenced in README.md.

**Comment by wesyoung** [comment]
can you provide a log of how you ran this (and which platform??)

it should have been run like:

```
$ cd massive-octo-spice-xxxx
$ sudo bash ./hacking/platforms/easybutton.sh
```

if you weren't using the curl command...

**Comment by adamyala** [comment]
I'd like to reopen this issue. I got the same error when running the easy button on a fresh ubuntu 14 x64 box.

I ran:
```
sudo apt-get install -y git && 
git clone https://github.com/csirtgadgets/massive-octo-spice.git && 
cd massive-octo-spice && 
git checkout 2.00.03 && 
sudo bash ./hacking/platforms/easybutton.sh
```

Then after lots of installing got:
```
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Enabling module socache_shmcb.
Enabling module ssl.
See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
Enabling module proxy.
Considering dependency proxy for proxy_http:
Module proxy already enabled
Enabling module proxy_http.
To activate the new configuration, you need to run:
  service apache2 restart
adding user: cif
Adding user `www-data' to group `cif' ...
Adding user www-data to group cif
Done.
starting elastic search
 Adding system startup for /etc/init.d/elasticsearch ...
   /etc/rc0.d/K10elasticsearch -> ../init.d/elasticsearch
   /etc/rc1.d/K10elasticsearch -> ../init.d/elasticsearch
   /etc/rc6.d/K10elasticsearch -> ../init.d/elasticsearch
   /etc/rc2.d/S95elasticsearch -> ../init.d/elasticsearch
   /etc/rc3.d/S95elasticsearch -> ../init.d/elasticsearch
   /etc/rc4.d/S95elasticsearch -> ../init.d/elasticsearch
   /etc/rc5.d/S95elasticsearch -> ../init.d/elasticsearch
 * Starting Elasticsearch Server                                                                                         [ OK ]
removing old elastic search templates
./ubuntu.sh: line 100: ./configure: No such file or directory
```

**Comment by wesyoung** [comment]
if you're checking it out manually; make sure you ```bash autogen.sh``` so autoconf can build the .in files...

**Comment by wesyoung** [comment]
which also means you need to have the correct autoconf dev tools installed:

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/hacking/platforms/easybutton_curl.sh#L35

**Comment by adamyala** [comment]
I think I understand where people are getting confused. I was following this build guide.

https://github.com/csirtgadgets/massive-octo-spice/wiki/PlatformUbuntu14

Which has the snippet:
```
$ tar -zxvf cif-2.xx.xx.tar.gz
$ cd cif-2.xx.xx
$ sudo bash ./hacking/platforms/easybutton.sh
```

I assumed the entire thing would be:
```
wget https://github.com/csirtgadgets/massive-octo-spice/archive/2.00.03.tar.gz && 
tar -zxvf 2.00.03.tar.gz && 
cd massive-octo-spice-2.00.03 && 
sudo bash ./hacking/platforms/easybutton.sh
```

But the bash code that runs `autogen.sh` is on the `develop` branch but not `2.00.03`. So I changed it to:
```
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y htop build-essential automake autoconf git && 
wget https://github.com/csirtgadgets/massive-octo-spice/archive/2.00.03.tar.gz && 
tar -zxvf 2.00.03.tar.gz && 
cd massive-octo-spice-2.00.03 && 
bash autogen.sh && 
sudo bash ./hacking/platforms/easybutton.sh
```
and I get an error saying that the cif directory isn't a valid git project. So I went back to the github cloning method with:
```
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y htop build-essential automake autoconf git && 
git clone https://github.com/csirtgadgets/massive-octo-spice.git && 
cd massive-octo-spice && 
git checkout 2.00.03 && 
bash autogen.sh && 
sudo bash ./hacking/platforms/easybutton.sh
```

This method was able to finish the install successfully.

If I'm pulling from github, should I even be on the `2.00.03` branch? Or should I just use `develop` since it has more baked into it?

Also, did I follow the build process correctly? If not, what should I be doing.

**Comment by wesyoung** [comment]
hey bud, yes, this is a bit ... funky. long story short; i updated the wiki:

https://github.com/csirtgadgets/massive-octo-spice/wiki/PlatformUbuntu14/_compare/8b327cb7c7e198a78bdcb021f3f60780ea344d6b...e86a1f38edb3875f78fd75902900c26ac76f9687

fwiw, we're learning from all our "why the hell would you do things that way!?" .. mistakes and building those lessons learned into v3 (python, ansible, etc):

https://github.com/csirtgadgets/bearded-avenger

it's not 100% yet, but actually starting to get things into pypi for a push towards "a less insane build and deployment process, maybe even a PPA".

let me know if those new sets of steps work OK for you.

**Comment by adamyala** [comment]
Thank you for the updated documentation.

These new steps built successfully. You can close out this issue.

For additional questions, should I make another issue or is there a medium you prefer?

**Comment by wesyoung** [comment]
doesn't matter, log them here as a ticket or the google group for more discussion bits:

https://groups.google.com/forum/#!forum/ci-framework
