### ISSUE TITLE
Tag- Ransomeware

### ISSUE THREAD

**Issue by diveshshah** [csirtgadgets/massive-octo-spice#449]
Hi Team,

In feed creation can we tag ransomeware??
As in document ransomeware tag in not mention.

Thanks
Divesh Shah

**Comment by wesyoung** [comment]
you can set tags to be whatever you want them to be.

**Comment by diveshshah** [comment]
Dear Team, 

As i follow document ,no where tag of ransomware mention . 

I tried to type query which include tag of ransomware, that was not giving output. 


So please guide how we can achieve. 

Thanks 
Divesh Shah
