### ISSUE TITLE
feed: Compromised stores that contain Javascript malware 

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/massive-octo-spice#455]
https://gitlab.com/gwillem/public-snippets/snippets/28813

**Comment by wesyoung** [comment]
https://gitlab.com/gwillem/public-snippets/snippets/28813/raw

**Comment by wesyoung** [comment]
similar:

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/src/rules/default/blocklist_de.yml

**Comment by Gitoffthelawn** [comment]
@wesyoung It looks like the gwillem list is no longer available on gitlab,.  Do you know if it has a new source that is being updated?

**Comment by wesyoung** [comment]
no, but thanks for brining this up. we'll have to remove it. these things come and go :(
