### ISSUE TITLE
Is CIF latest version is compatible with Ubantu 16.04 version

### ISSUE THREAD

**Issue by priyamalik** [csirtgadgets/massive-octo-spice#459]
Hi,

I am going to install latest ubantu version 16.04.
Please help me to know that is it compatible with CIF latest version?
(Have you released any other version also other than massive-octo-spice?)

Thanks and Regards,
Priya Malik

**Comment by wesyoung** [comment]
we haven't really tested much with 16.xx, and with teh switch to systemd, i'm pretty sure it'll fail. that said; we're working on deployment for 16 in v3:

https://github.com/csirtgadgets/bearded-avenger/issues/63

and happy to take PR's.
