### ISSUE TITLE
Set user agent in feeds

### ISSUE THREAD

**Issue by byrug4** [csirtgadgets/massive-octo-spice#460]
A user agent field would be fine to user for feeds.
There are feeds (eg.: clean mx) require customized user agent settings:
http://support.clean-mx.de/clean-mx/xmlviruses.php

Linux cifprod1 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 14.04.4 LTS \n \l

CIF v2

**Comment by wesyoung** [comment]
was there a question in there somewhere? :)

we do set the user-agent:

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/src/lib/CIF/Smrt/Fetcher.pm#L28
