### ISSUE TITLE
CIF Connection Issue

### ISSUE THREAD

**Issue by priyamalik** [csirtgadgets/massive-octo-spice#462]
My CIF was working fine, from from 2-3 days it was not showing output.
So I ran command 
CIF -p
and it is showing  below error.

[2016-11-24T12:07:57,239Z][WARN]: unauthorized
[2016-11-24T12:07:57,239Z][FATAL]: unauthorized

**Comment by priyamalik** [comment]
Also I ran below command to get output into csv file (Earlier it was giving output) but now it is showing below error.
soc@soc:~$ cif --feed --otype ipv4 --today -f csv > testing.csv
<!DOCTYPE html>
<html>
  <head><title>Server error</title></head>
  <style>
      body { background-color: #caecf6 }
      #raptor {
        background: url(/mojo/failraptor.png);
        height: 488px;
        left: 50%;
        margin-left: -371px;
        margin-top: -244px;
        position:absolute;
        top: 50%;
        width: 743px;
      }
    </style>
  <body><div id="raptor"></div></body>
</html>
 at /usr/local/bin/cif line 324.

**Comment by wesyoung** [comment]
anythin in the server logs? 

i'm guessing you might be out-growing your elasticsearch instance...

**Comment by amateur-professional** [comment]
Recently this has begun to happen to me when the machine re-boots or some cif-service (haven't nailed down which one) is restarted. I checked cif-tokens and both tokens I had set (one for the cif user and one for myself) are gone. 

It's not the Elasticsearch instance size, either, because we're not keeping data older than 7 days.

**Comment by wesyoung** [comment]
what does the cluster status look like ?

**Comment by amateur-professional** [comment]
Same as it always has.

>> curl -XGET 'http://localhost:9200/_cluster/health?pretty'
{
  "cluster_name" : "elasticsearch",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 10,
  "active_shards" : 10,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 10
}

**Comment by wesyoung** [comment]
yellow is no good. means something is going on at the local level... depending on your setup (and amount of data) you may want to google around for "unassigned_shards" ... get an idea of what's going on.

**Comment by amateur-professional** [comment]
From the ES 1.4 KB on cluster health: 

> The cluster health status is: green, yellow or red. On the shard level, a red status indicates that the specific shard is not allocated in the cluster, yellow means that the primary shard is allocated but replicas are not, and green means that all shards are allocated. 

We have not created replicas for this instance, which is probably why we are getting the yellow status, but I don't believe it's a problem right now as the data in CIF doesn't need to be particularly resilient.

**Comment by wesyoung** [comment]
dunno then. when i've seen tokens start 401'ing on me, usually elasticsearch is yellow and not returning the proper results. my hunch is you should try to get it into a green state and from there it'll be a little easier to figure out what the issue is... (i think).
