### ISSUE TITLE
Database Location

### ISSUE THREAD

**Issue by priyamalik** [csirtgadgets/massive-octo-spice#464]
Hi All,

As from given source code, I got to know that we are fetching data from 29-30 sources and around 60 urls.
When I am doing query (cif --feed --otype ipv4 -f stix), it is showing me output, But I want to know that from where my query is fetching data OR what is location of this database.
Is data is getting stored at my local system or somewhere else.

Thanks and Regards,

**Comment by wesyoung** [comment]
google "elasticsearch" :)

**Comment by wesyoung** [comment]
also see my resp to #463
