### ISSUE TITLE
EasyButton failure - ubuntu.sh - Net::SSLeay and other failues in cpan dep GeoIP2@0.040005

### ISSUE THREAD

**Issue by cjhc** [csirtgadgets/massive-octo-spice#467]
Net::SSLeay fails, apparently due to a missing dep for libssl-dev in a default Ubuntu Server 14.04LTS build (only optional package selection was OpenSSH server).

**Comment by wesyoung** [comment]
are you starting with 14.04.4 or 14.04.5 ?

**Comment by wesyoung** [comment]
i think this is fixed in 2.00.06- tested against ubuntu 14.05.5
