### ISSUE TITLE
migration issue

### ISSUE THREAD

**Issue by villain** [csirtgadgets/massive-octo-spice#475]
when trying to run the v1 migration script:

cif@ubuntu:/massive-octo-spice/v1migration$ perl -I../src/lib -Ilib bin/migrate-data.pl -h
Can't use string ("1") as an ARRAY ref while "strict refs" in use at /usr/local/share/perl/5.18.2/Google/ProtocolBuffers.pm line 308.
Compilation failed in require at bin/migrate-data.pl line 18.
BEGIN failed--compilation aborted at bin/migrate-data.pl line 18.
cif@ubuntu:/massive-octo-spice/v1migration$

**Comment by wesyoung** [comment]
(note; i never really got this to work ... well. we just ended up starting from scratch with new data in v2)

it looks like there might be a bug in 0.12, try 0.11:

`sudo cpanm install http://www.cpan.org/authors/id/S/SA/SAXJAZMAN/protobuf/Google-ProtocolBuffers-0.11.tar.gz`
