### ISSUE TITLE
cif-router.conf values ingored !

### ISSUE THREAD

**Issue by Nibor62** [csirtgadgets/massive-octo-spice#484]
Bonjour,

Found another issue while trying to set back Elasticsearch index naming from "cif.observables-YYY.MM" to "cif.observables-YYY.MM.DD" (which is, by the way, still the way your (contrib) Kibana dashboard is expecting indices).
Config file "cif-router.conf" doesn't have any effect on it.
```yaml
router:
  storage_index_partition: days
```

Absolutly all the field available in config file are set if nothing have been specified yet:
https://github.com/csirtgadgets/massive-octo-spice/blob/a6994e8725a06daaeea8f70578f0322f96346e72/src/bin/cif-router#L133-L140
But, all this value have a default value :
https://github.com/csirtgadgets/massive-octo-spice/blob/a6994e8725a06daaeea8f70578f0322f96346e72/src/bin/cif-router#L22-L40
meaning that actually, config file values are never used !

Before I send you a PullRequest, what should be the priority order for these field (defaultValues, cmdArgs, configFile) ?

**Comment by wesyoung** [comment]
should be: defaultValuess, configFile, cmdArgs.

[actually working on the ES stuff in v3 so will be sure to carry this info forward as it has some of the same concepts]

good find.
