### ISSUE TITLE
CIF intelligence provider detail

### ISSUE THREAD

**Issue by diveshshah** [csirtgadgets/massive-octo-spice#496]
Dear team,

How we can find out threat intelligence provider  list or detail in CIF.

Can you please share List of  threat intelligence provider  of CIF

Thanks
Divesh Shah

**Comment by wesyoung** [comment]
see:

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/FAQ
https://github.com/csirtgadgets/massive-octo-spice/wiki/Exploring-the-OSINT-pre-configured
https://github.com/csirtgadgets/massive-octo-spice/tree/develop/src/rules/default
