### ISSUE TITLE
CIF Integrate with IBM 

### ISSUE THREAD

**Issue by shrishti01** [csirtgadgets/massive-octo-spice#498]
Hello,

can you please tell me how can i integrate IBM feeds in my CIF server database. 

Thanking in advance

**Comment by wesyoung** [comment]
hi,

+ do you have publicly available examples ?
+ do those examples closely match any of these? https://github.com/csirtgadgets/bearded-avenger/tree/master/rules/default

**Comment by shrishti01** [comment]
Hi,

I don't have any publicly available example ..
But I want to integrate it, Please guide me or provide me with related scripts....


Thanks In advance

**Comment by wesyoung** [comment]
do their feeds match anything in that rules directory i linked to? that'd be a great place to start- find a feed in there that matches closely to your IBM stuff and then start tweaking it...

**Comment by shrishti01** [comment]
HI,
I think we have to generate a new rule for this I tried doing it but not getting any output .

I am attaching my file with it ..
Hoping for help..

Thanks in advance 

[xforce ibm .txt](https://github.com/csirtgadgets/massive-octo-spice/files/1621411/xforce.ibm.txt)

**Comment by shrishti01** [comment]
Hi,

Can you please let us know , how to provide external source feeds to installed cif server.
Basically we have to integrate new sources in our cif server for threat intelligence feeds.

Your guidance will be of great help.

Thanks in Advance

**Comment by wesyoung** [comment]
you probably want to "cron" that curl command */15 or so to write the feed to something like, `/tmp/xforce.txt`, then set the 'remote' to 'file:///tmp/xforce.txt' and try again.

if you're just starting out- you may wanna re-try with CIFv3 as v2 is going EOL soon.

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki
