### ISSUE TITLE
CIFIP File Issue

### ISSUE THREAD

**Issue by devangraval007** [csirtgadgets/massive-octo-spice#500]
Hello,

While exporting IP list feed from CIF server. We are getting this error frequently all though other feeds we are not getting any errors.

Please guide needful step to profrom on CIF server to avoid this error.

Thanking in advance.
![39](https://user-images.githubusercontent.com/35298048/35208619-5007ac1c-ff6f-11e7-803e-ff6fa3f28d59.png)

**Comment by wesyoung** [comment]
i'm guessing the box needs more memory- usually those are from cif-starman crashing (or ES taking too much memory on a query). the logs would help highlight that.

https://github.com/csirtgadgets/massive-octo-spice/wiki/Troubleshooting-cif
