### ISSUE TITLE
CIF Server Logs file

### ISSUE THREAD

**Issue by devangraval007** [csirtgadgets/massive-octo-spice#501]
Hello Sir,

Hope you are doing well. I would like to ask you. how can we get log file of CIF server.
I mean, where i can find CIF server logs file in the system.

Thanks in advance.

**Comment by coonsmatthew** [comment]
Hello 

CIF server log files should all be in `/var/log`

They are broken up by CIF server function, for example: 
`/var/log/cif-smrt.log`
`/var/log/cif-worker.log`

Let me know if this isn't what you're looking for!

Thanks.
